getsentry/seer

src/seer/seer.py, src/seer/trend_detection/trend_detector.py
Increasing the threshold to 10% because a regression under 10% doesn't seem as useful
=> chore(trendsv2): Update analysis threshold to 10%

src/seer/seer.py, src/seer/trend_detection/trend_detector.py
add in a boolean to check if breakpoint analysis is being used for trends or not 
- will continue with midpoint analysis for trends, otherwise will just move on to the next transaction
=> for trends boolean

src/seer/seer.py, src/seer/trend_detection/trend_detector.py
- add an additional requirement that the last 24h of data meets `min_change` and `min_pct_change`
=> feat: require last 24h to also be regressed 

.envrc, .gitignore, .pre-commit-config.yaml, Dockerfile, Makefile, README.md, pyproject.toml, requirements.txt
First step, going to build on this with test improvements, mypy, and an optional dockerized dev environment.
=> Adding pre-commit hooks, black formatter, isort

src/seer/seer.py
Allow us to track performance in sentry.io to investigate timeout issues.
=> Enable tracing

src/seer/app.py, src/seer/grouping/grouping.py, src/seer/schemas/seer.py, src/seer/schemas/seer_api.json
- require stacktrace and message as inputs to a similarity call
- add levenshtein (edit) distance metric for message similarity
=> feat(grouping): add message similarity

supervisord.conf
Merge this when ready to enable the celeryworker and run autofix
=> chore: Enable celery worker process

Dockerfile, celeryworker.sh, docker-compose.yml, supervisord.conf
CELERY_WORKER_ENABLE env var will disable/enable the celery worker.
Tested locally.
=> chore: enable celery worker with env CELERY_WORKER_ENABLE

gocd/pipelines/seer.yaml
We need this for seer-autofix service
=> chore(gocd): Add seer-autofix to GoCD

src/seer/automation/autofix/agent_context.py
Stop outputting the price of the GPT tokens on the PR but still output the token stats for debugging purposes
=> fix(autofix): Stop putting the price in the pr

src/seer/automation/autofix/autofix.py, src/seer/automation/autofix/repo_client.py
👋 Hi there! This PR was **NOT** automatically generated 🤖
Updates the pr format to match what you're seeing here.
1. ...
2. ...
None
- **If these changes were incorrect, please close this PR and comment explaining why.**
- **If these changes were incomplete, please continue working on this PR then merge it.**
- **If you are feeling confident in my changes, please merge this PR.**
This will greatly help us improve the autofix system. Thank you! 🙏
If there are any questions, please reach out to the [AI/ML Team](https://github.com/orgs/getsentry/teams/machine-learning-ai) on [#proj-suggested-fix](https://sentry.slack.com/archives/C06904P7Z6E)
- 15 Jenn minutes
=> feat(ai-autofix): New Pull Request format

src/seer/automation/autofix/prompts.py
Tested locally with an adversarial input (a bad issue)
=> fix(ai-autofix): Add a line to execution prompt to avoid doom loops

src/seer/automation/autofix/repo_client.py
=> feat(ai-autofix): Make the PR a draft pr

src/seer/automation/autofix/codebase_context.py, src/seer/automation/autofix/tools.py
this is why you type your arguments
=> fix(ai-autofix): Correctly pass the base sha

src/seer/app.py, src/seer/grouping/grouping.py
- fix bug allowing indices from outside of a project to be referenced
- switch model serialization/loading to properly load all files needed for inference
=> fix bugs and update jia model load

src/seer/rpc.py, src/seer/utils.py
Fixes [TIMESERIES-ANALYSIS-SERVICE-29](https://sentry.sentry.io/issues/4991819556/)
=> fix(ai-autofix): Make enum json serializable

src/seer/automation/agent/agent.py, src/seer/automation/agent/models.py, src/seer/automation/autofix/autofix.py, src/seer/automation/autofix/prompts.py, src/seer/automation/autofix/tasks.py, src/seer/automation/autofix/tools.py, src/seer/automation/codebase/repo_client.py, src/seer/automation/utils.py, tests/automation/agent/test_utils.py
- OpenAI Tool use passes the argument as a json string, and because we work with code, code snippets often contain JSON characters that confuse JSON parsers
- Create file and delete file weren't working
- A JSON parser that uses tree-sitter-languages to only parse out valid characters
- Better support cases of create and delete file
- Little prompt engineering tweaks to adjust the llm tool use and also optimize the execution.
=> fix(ai-autofix): Fix tool use issues

src/seer/app.py, src/seer/automation/autofix/autofix.py, src/seer/automation/autofix/models.py, src/seer/automation/codebase/codebase_index.py, src/seer/schemas/seer.py, src/seer/schemas/seer_api.json, tests/automation/autofix/test_autofix.py
- Remove the `repo_` prefix from the `RepoDefinition` pydantic model
- Remove `OldAutofixRequest`
=> ref(autofix): Update request payload to match sentry side

src/seer/json_api.py
=> chore: add sentry logs to json_api

src/seer/automation/autofix/autofix.py, src/seer/automation/autofix/models.py, src/seer/automation/codebase/repo_client.py
Resolves #289 
- Links to the issue short id on the PR, which should link to the sentry issue when squashing the commit
- Says who triggered the autofix, very useful now that we expanded support to multiple projects
=> feat(autofix): Say who clicked on PR + fixes issue short ID

src/seer/automation/codebase/codebase_index.py, src/seer/utils.py
Should fix [TIMESERIES-ANALYSIS-SERVICE-2S](https://sentry.sentry.io/issues/5029600041/)
=> fix(autofix): Batching chunk inserts

src/seer/automation/autofix/prompts.py
Just added my 2c based on the current prompts, feel free to close if you don't think these will help. Hoping this helps resolve the doom loop issue identified [here](https://github.com/getsentry/timeseries-analysis-service/issues/300).
Also just some general purpose strengthening of language (should -> must) and (sadly) removing the gaslighting prompts.
=> feat(autofix): Tweak some of the prompts

src/seer/automation/autofix/autofix.py, src/seer/automation/autofix/prompts.py, src/seer/automation/autofix/tools.py, src/seer/automation/autofix/utils.py, tests/automation/autofix/test_autofix_tools.py, tests/automation/autofix/test_autofix_utils.py
New code manipulation tool that should reduce incorrect replacements with invalid characters, indents, etc while also improving code quality. Prompts GPT-4 to actually perform the replacement.
Diagram provided below to explain how this works.
+ Happy path test case although ideally we integration test this with GPT, don't want to call GPT everytime we run CI.
=> feat(autofix): Improved snippet replacement tool using llm

src/seer/automation/autofix/autofix.py, src/seer/automation/autofix/event_manager.py, src/seer/automation/autofix/models.py, src/seer/automation/codebase/repo_client.py
Resolves #244 
Need to time the merge with frontend PR
=> feat(autofix): Implement logging for frontend

src/seer/automation/autofix/autofix.py, src/seer/automation/autofix/prompts.py, src/seer/automation/autofix/tasks.py, src/seer/automation/autofix/tools.py, tests/automation/autofix/test_autofix_tools.py
Moves instructions/information on the current topic at hand to the user prompt in all the prompts along with minor changes to the prompts that should make the agents a little more robust.
- Prevents unit test generation
- More focused, actionable output
- Should perform the task in less steps and get to a solution faster
[Example run of all these prompts and tracing in action](https://smith.langchain.com/public/e0bcfaa6-6b69-49bc-a35a-e73a804be1cb/r)
=> ref(autofix): Refactor all the prompts to be more robust

asyncworker.sh, src/seer/automation/autofix/autofix.py, src/seer/automation/autofix/event_manager.py, src/seer/automation/autofix/models.py, src/seer/automation/autofix/tasks.py, src/seer/automation/state.py, src/seer/task_factory.py, src/seer/tasks.py, supervisord.conf
Will annotate in comments.
Tested e2e locally with autofix
=> fix(async): Get async worker to work with autofix e2e

src/seer/automation/agent/client.py, src/seer/automation/agent/models.py, src/seer/automation/autofix/models.py, src/seer/automation/autofix/tasks.py, src/seer/generator.py, src/seer/rpc.py, src/seer/task_factory.py, src/seer/tasks.py, src/seer/utils.py, tests/automation/autofix/test_autofix.py, tests/generators.py, tests/test_rpc.py
Getting more tests in, fixing RPC
=> More tests

src/seer/app.py, src/seer/automation/autofix/tasks.py, supervisord.conf, tests/test_seer.py
Restore just using celery worker.
=> Removing async worker

.github/workflows/validate-pipelines.yml, gocd/pipelines/seer.yaml
Updating the GoCD pipeline to use the new repo name.
=> Updating the GoCD pipeline to use seer

src/seer/app.py, src/seer/automation/autofix/autofix.py, src/seer/automation/autofix/components/assessment/component.py, src/seer/automation/autofix/components/assessment/models.py, src/seer/automation/autofix/components/assessment/prompts.py, src/seer/automation/autofix/components/planner/component.py, src/seer/automation/autofix/components/planner/models.py, src/seer/automation/autofix/components/planner/prompts.py, src/seer/automation/autofix/models.py, src/seer/automation/autofix/prompts.py, src/seer/automation/autofix/tasks.py
Makes autofix more receptive to instructions from the user. Changes the concept of "additional context" to "instruction"
=> feat(autofix): Get autofix to be more responsive to instructions

notebooks/create_dataset.ipynb
Create a new Langchain dataset for autofix validation using JSON data that was previously exported.
=> chore: Create a new langchain validation dataset from json data

.envrc, .gitignore, .pre-commit-config.yaml, README.md, pyproject.toml, setup.py
This is a bunch of autoformatting which happened as I was touching various files, pulled into a separate PR so as not to pollute other PRs with irrelevant changes. No changes otherwise.
=> chore(dev): Apply autoformatter to various config files

src/seer/severity/severity_inference.py
this calls the `.encode` function before verifying that the model initialization is complete, ensuring a warm start
=> fix(severity): ensure warm start for severity model

requirements.txt, src/seer/automation/agent/agent.py, src/seer/automation/agent/client.py
Use the new `gpt-4-turbo-2024-04-09`
=> chore(autofix): Use new gpt4 turbo 04-09

src/seer/automation/autofix/pipelines.py, src/seer/automation/codebase/codebase_index.py
Been noticing hallucinations of PRs, this fixes the below by not generating a diff or pr title/description for no changes:
=> fix(autofix): Fix hallucinating change description

src/seer/automation/autofix/components/root_cause/component.py
Fixes [SEER-4C](https://sentry.sentry.io/issues/5245547145/)
=> fix(autofix): Add more leaf tags to root cause xml escape

benchmark/locustfile.py
add locust to start benchmarking performance
=> add locust benchmark

benchmark/locustfile.py
use more realistic looking stack traces
=> update test data for requests

src/seer/app.py, src/seer/automation/codebase/models.py, src/seer/automation/codebase/repo_client.py, src/seer/automation/codebase/tasks.py, tests/automation/codebase/test_repo_client.py
Endpoint `/v1/automation/codebase/repo/check-access` to check if our github integration has the necessary permissions to access the repo in question, in this case, "contents" == "write" and "pull_request" == "write"
=> feat(autofix): Repo access check endpoint

src/seer/automation/codebase/namespace.py
Fixes [SEER-52](https://sentry.sentry.io/issues/5303418337/)
=> fix(codebase): Fix workspace loading in NamespaceManager

src/seer/automation/codebase/storage_adapters.py, tests/automation/codebase/test_storage_adapters.py
Fixes [SEER-51](https://sentry.sentry.io/issues/5303418258/)
=> fix(storage): Fix gcs storage delete being an iterator

src/seer/automation/codebase/codebase_index.py, src/seer/automation/codebase/namespace.py
=> ref: Namespace logging

src/seer/bootup.py
change grouping default logger to log debug -- trying to debug cuda stuff on container.
=> fix: change group logger to debug

src/seer/automation/codebase/codebase_index.py
Accidentally left this in from local dev...should stop doing this and make it a dev flag or smth
=> fix: remove truncated documents

src/seer/app.py, src/seer/grouping/grouping.py, src/seer/schemas/seer_api.json, tests/seer/grouping/test_grouping.py, tests/test_seer.py
Re-doing this [PR](https://github.com/getsentry/seer/pull/480/) using hash column (got the original PR in a bad state locally)
=> feat(similarity_embedding): Create bulk insert endpoint

src/seer/automation/codebase/code_search.py
So it groups together instead of spamming us
=> fix(autofix): Log an exception when unable to read file instead

src/seer/anomaly_detection/__init__.py, src/seer/anomaly_detection/anomaly_detection.py, src/seer/anomaly_detection/anomaly_detection_di.py, src/seer/anomaly_detection/detectors/__init__.py, src/seer/anomaly_detection/detectors/anomaly_detectors.py, src/seer/anomaly_detection/detectors/mp_config.py, src/seer/anomaly_detection/detectors/mp_scorers.py, src/seer/anomaly_detection/detectors/mp_utils.py
=> chore(dynamic alert thresholds) Moving to dependency injection for inversion of control

src/seer/configuration.py
=> fix: Make the sentry github app keys warnings instead

src/seer/bootup.py, src/seer/configuration.py, src/seer/langfuse.py, tests/test_langfuse.py
1. Langfuse env vars in `AppConfig`
2. Dependency injected langfuse 
3. Util method to add tags to a currently running trace
=> feat: Langfuse in DI + disable in tests

src/seer/anomaly_detection/detectors/anomaly_detectors.py, src/seer/anomaly_detection/detectors/mp_scorers.py, src/seer/anomaly_detection/detectors/mp_utils.py
Merge stream and batch scoring logic to reduce code redundancy.
=> chore(dynamic alert thresholds): scorer code deduplication

src/seer/grouping/grouping.py, tests/seer/grouping/test_grouping.py
=> chore(grouping): improve reranking logging

src/seer/app.py, src/seer/automation/autofix/models.py, src/seer/automation/autofix/tasks.py, tests/test_seer.py
Also just passes the pydantic model to the eval method
=> feat(evals): Add description and multiple runs per item

src/seer/automation/autofix/components/root_cause/models.py, src/seer/automation/autofix/components/root_cause/prompts.py, src/seer/automation/autofix/evaluations.py, tests/automation/autofix/components/coding/test_coding_models.py, tests/automation/autofix/components/test_root_cause.py
Adds repository name alongside file path in code snippets. This is to support code hyperlinks on the frontend. Issue #1004 
Sentry PR: https://github.com/getsentry/sentry/pull/75610
=> feat(autofix): Add repo name to root cause code context snippets

src/seer/automation/agent/agent.py, src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/coding/models.py, src/seer/automation/autofix/components/coding/prompts.py, src/seer/automation/autofix/components/root_cause/component.py, src/seer/automation/autofix/components/root_cause/prompts.py, tests/automation/autofix/components/test_root_cause.py
Changes detailed in below comments.
- Increases scores a noticeable amount.
- Reduces overall error rate from 30% to 18% 
- Reduces root cause error rate from 15% to 4%
=> feat(autofix): Increase stability with prompt engineering, parsing improvements, etc

README.md
Add description and n runs documentation
=> chore: Update eval readme

src/seer/automation/autofix/tools.py
For example, an incorrect `list_directory` tool call could return this:
```
<no entries found in directory 'seer/automation/codebase'/>
<did you mean>
src/seer/automation/codebase/
</did you mean>
```
So now the agent has context to correct itself on the next turn instead of searching aimlessly.
=> (autofix): Suggest similar paths if ls or expand document tools fail

requirements.txt, src/seer/app.py, src/seer/automation/summarize/issue.py, src/seer/automation/summarize/models.py, tests/automation/summarize/test_issue.py
Introduces the `/v1/automation/summarize/issue` endpoint. 
The ai pipeline follows:
- Initial pass w/ unstructured CoT and answer
- Second pass to extract structured output.
=> feat(issue-summary): Initial working issue summary endpoint

src/seer/automation/summarize/issue.py, tests/automation/summarize/test_issue.py
Nice quality summaries, conditionally returning customer impact summary, and affected functionality--all in one structured output prompt.
Issue #1043
=> (issue summary) Update issue summary prompt

src/celery_app/tasks.py
Enables the autofix cleanup task
=> chore: Enable hourly autofix run cleanup task

src/seer/automation/summarize/issue.py, src/seer/automation/summarize/models.py, tests/automation/summarize/test_issue.py
From limited testing:
1. Now we don't just reiterate minified JS errors
2. We don't just restate the error message in general
3. Added a new "headline" in the response that we can make use of
4. Verbosity and fluffy speech is reduced
5. Reduced overlap between headline and summary/impact so that they are all more valuable together
=> (issue summary) Improve issue summary prompt

src/seer/automation/models.py, tests/automation/autofix/test_models.py
Issue #1060 
Just default to None if we don't have a function name, instead of making one up that confused the summarizer.
=> (issue summary) Remove confusing unknown_function value

requirements.txt
Fixes [CVE-2024-35195](https://data.safetycli.com/v/71064/97c/)
You can view the changes between the versions [here](https://github.com/psf/requests/compare/v2.32.0...v2.32.2).
=> Update requests library

src/seer/app.py, src/seer/automation/summarize/issue.py, src/seer/automation/summarize/models.py, tests/automation/summarize/test_issue.py
tracks org slug org id project id and group
=> feat(issue-summary): better langfuse tracking

src/seer/automation/autofix/autofix_context.py, tests/automation/autofix/test_autofix_context.py
Fix PR creation failure from customer email. We need to find the changes step by key not id.
=> fix(autofix): Fix pr creation failure

src/seer/anomaly_detection/accessors.py, src/seer/anomaly_detection/anomaly_detection.py, src/seer/anomaly_detection/detectors/anomaly_detectors.py, src/seer/app.py
- Enable Tracing for Store and Detect endpoints for Anomaly Detection
- Capture Exceptions through Sentry for each endpoint
- Traces are tagged with `organization_id` and `project_id` to filter in Sentry.io
Notes: 
- Explicit Metrics were not included as Performance monitoring captures relevant information (ie: duration of transactions and their spans)
- Logs for endpoints were already handled
Closes #881
=> Implement Sentry SDK in Anomaly Detection

src/seer/automation/summarize/issue.py, tests/automation/summarize/test_issue.py
Just some prompt improvements for issue summary to handle trace connected issues a bit better
=> (issue summary) Prompt improvements

src/seer/automation/models.py
Resolving this Sentry issue: https://sentry.sentry.io/issues/5791280955/?project=6178942
=> fix(issue summary): Make exception type optional to prevent validation error

src/seer/anomaly_detection/detectors/window_size_selectors.py, tests/seer/anomaly_detection/detectors/test_window_size_selector.py
- Set up upper bound to avoid `window_size` overflow when hitting `_score()` (upper limit is np.integer max size which is 2**63 - 1)
- Write basic unit tests to confirm functionality
=> fix(anomaly detection): handle overflow for SuSS algorithm

src/seer/json_api.py
Adding debug info to troubleshoot auth failures seen in calls from the subscription processor.
=> Debug auth error

src/seer/automation/summarize/replays.py, src/seer/automation/utils.py, tests/automation/summarize/test_replays.py
Replay summary AI pipeline work, not callable via endpoint yet.
=> feat(summaries): Add replay summary

src/seer/anomaly_detection/detectors/mp_scorers.py
Disabling peak-trough detection until its refined further
=> chore(anomaly-detection) Disable peak-trough detection

src/seer/automation/autofix/components/coding/component.py
Re-enable Claude for the coding agent, since potential IAM fix is in. Hopefully it works this time.
=> (autofix) Switch coding to claude (again)

src/seer/anomaly_detection/accessors.py, src/seer/anomaly_detection/anomaly_detection.py, src/seer/anomaly_detection/models/external.py, src/seer/app.py
Add a new endpoint to delete a previously stored alert
=> chore(dynamic alert thresholds) Delete alert data endpoint

src/seer/grouping/grouping.py
Add span for individual record insert in bulk record insertion
=> chore(similarity): Add span to individual record insert

src/seer/app.py, src/seer/grouping/grouping.py
Add try catch and logging for integrity error in insert grouping records
=> fix(similarity): Add try catch around insert in grouping records

src/seer/automation/agent/agent.py, src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/coding/models.py, src/seer/automation/autofix/components/coding/prompts.py, src/seer/automation/autofix/components/insight_sharing/component.py, src/seer/automation/autofix/components/root_cause/component.py, src/seer/automation/autofix/components/root_cause/models.py, src/seer/automation/autofix/components/root_cause/prompts.py, src/seer/automation/autofix/evaluations.py, src/seer/automation/autofix/event_manager.py, src/seer/automation/autofix/models.py, src/seer/automation/autofix/steps/coding_step.py, src/seer/automation/autofix/steps/root_cause_step.py, src/seer/automation/autofix/tasks.py, src/seer/automation/autofix/tools.py, tests/automation/agent/test_agent.py, tests/automation/autofix/components/test_insight_sharing.py, tests/automation/autofix/test_autofix_evaluations.py, tests/automation/autofix/test_autofix_event_manager.py, tests/automation/autofix/test_autofix_tasks.py, tests/automation/autofix/test_models.py
Gives Autofix the option to ask the user a question, and continue analysis once they respond.
Also adds a way to disable interactive features when requesting Autofix to start (good for evals, copilot)
=> feat(autofix): Add Q&A interaction

src/seer/anomaly_detection/accessors.py, src/seer/anomaly_detection/detectors/__init__.py, src/seer/anomaly_detection/detectors/anomaly_detectors.py, src/seer/anomaly_detection/detectors/mp_scorers.py, src/seer/anomaly_detection/detectors/normalizers.py, src/seer/anomaly_detection/detectors/window_size_selectors.py, src/seer/anomaly_detection/models/timeseries_anomalies.py, src/seer/tags.py, tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py, tests/seer/anomaly_detection/detectors/test_mp_scorers.py, tests/seer/anomaly_detection/models/test_timeseries.py, tests/seer/anomaly_detection/models/test_timeseries_anomalies.py, tests/seer/anomaly_detection/test_accessors.py, tests/seer/anomaly_detection/test_anomaly_detection.py
This PR applies the sensitivity flag to the the anomaly detection logic.
=> chore(anomaly-detection) Use sensitivity flag

src/seer/automation/codebase/repo_client.py
this should fix pr creation in autofix
=> hotfix(autofix): repo client hotfix

gocd/templates/bash/deploy.sh
Need to entirely remove instead of comment
=> hotfix: entirely remove seer-gpu deploy script for now

src/seer/anomaly_detection/detectors/mp_scorers.py
- Adjust IQR bounds for scorer
=> Adjust Scorer Sensitivities

Dockerfile, grpcserver.sh
This is a follow up to https://github.com/getsentry/seer/pull/1195
Add traffic director bootstrap script to docker image and its execution.
=> change: Add grpc bootstrap

src/celery_app/tasks.py, src/seer/app.py, src/seer/automation/tasks.py, tests/test_celery.py
Continuing github copilot testing
=> (autofix) Change the intentional error

src/seer/automation/tasks.py
Continuing testing of GH copilot by intentionally creating an issue
=> (copilot): Change the error again

src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/coding/models.py, src/seer/automation/autofix/components/coding/prompts.py, src/seer/automation/autofix/event_manager.py, src/seer/automation/autofix/models.py, src/seer/automation/autofix/steps/coding_step.py, tests/automation/autofix/test_models.py
The user can optionally provide an instruction with the root cause selection, which is used in the prompt for the plan+code step.
=> feat(autofix) Add fix instruction to root cause selection

Makefile, requirements-constraints.txt, requirements.txt, src/seer/anomaly_detection/anomaly_detection_di.py, src/seer/anomaly_detection/detectors/anomaly_detectors.py, src/seer/anomaly_detection/detectors/location_detectors.py, src/seer/anomaly_detection/detectors/mp_scorers.py, tests/seer/anomaly_detection/detectors/test_location_detectors.py, tests/seer/anomaly_detection/detectors/test_mp_scorers.py
This PR uses Prophet model to predict expected value of time series and uses the prediction to check for direction. 
Anomaly detected with direction set to UP:
Anomaly not detected with direction set to DOWN:
=> feature(anomaly-detection): direction detection using prophet model

src/seer/automation/autofix/autofix_context.py, src/seer/automation/autofix/steps/change_describer_step.py, src/seer/automation/autofix/steps/coding_step.py, src/seer/automation/codebase/repo_client.py
1. Adds a comment to the suspect PR with a link to the new fix PR when generated.
2. Adds a link to the suspect PR in the fix PR description if one is provided.
=> feat(copilot): Add new comments for copilot, add extra info

src/seer/automation/autofix/steps/coding_step.py
=> fix(copilot/autofix): typing fix

src/seer/grouping/grouping.py, tests/seer/grouping/test_grouping.py, tests/test_seer.py
Stop sending message_distance from seer
Blocked by https://github.com/getsentry/sentry/pull/78346
=> ref(similarity): Stop sending message_distance from seer

src/celery_app/tasks.py, src/seer/automation/tasks.py, tests/test_celery.py
We were raising errors intentionally before to test GH Copilot. Removing that now.
=> fix(autofix): Remove intentional error

src/seer/automation/models.py
From the event payload, take information on whether an exception was handled or not, and pass it into the formatted event details that are passed into both issue summary and Autofix.
Resolves issue #1326, but we don't have any evals for Issue Summary, so can't say if it actually improved the impact summary. 
In Autofix evals, we saw a nice bump too (ignore the second row):
=> feat(autofix+issue summary): Add info on whether exceptions were handled or not

src/seer/automation/codebase/repo_client.py, src/seer/automation/codegen/unittest_step.py, tests/automation/codebase/test_repo_client.py, tests/automation/codegen/test_unit_test_step.py
If there is an error while trying to generate unit tests, post a comment to the original PR indicating that.  Current behaviour fails silently.
=> [feat] Post comment to PR is unit test generation does not complete 

.gc.staging.ignore, README.md, cloudbuild.staging.yml, requirements-constraints.txt, requirements.txt
Includes settings and ability to submit staging builds in cloud build format, rather than uploading entire image of local build.
Also bumps some library versions.
=> Better staging build support, bump versions

.github/CODEOWNERS
=> chore(dev): set up CODEOWNERS for seer repo

src/seer/automation/autofix/autofix_agent.py, tests/automation/autofix/test_autofix_agent.py
If the Autofix agent is about to hit the max iterations, and every 6 iterations, we prompt it saying that it's taking a while and should ask the user for help. #1369
=> feat(autofix): Prompt agent to ask questions if it's taking a while

src/seer/automation/autofix/prompts.py, src/seer/automation/summarize/issue.py, src/seer/automation/summarize/models.py, tests/automation/autofix/steps/test_root_cause_step.py, tests/automation/autofix/test_autofix_context.py, tests/automation/summarize/test_issue.py
New style of summary that contains "what's wrong", "trace", and "possible cause" sections.
=> feat(issue summary) Update issue summary with structured cards

src/seer/automation/autofix/evaluations.py, src/seer/automation/autofix/tasks.py, tests/automation/autofix/test_autofix_evaluations.py
During a full eval, we can now score the root cause along with it to get more signal
=> feat(evals): New eval with root cause scoring in it

src/seer/automation/autofix/components/root_cause/component.py
Switch root cause step to Sonnet for now. Haiku is better, but fixes error in prod while we wait for SRE to enable Haiku.
=> fix(autofix): Temp switch to sonnet

src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/coding/prompts.py, tests/automation/autofix/components/coding/test_coding_component.py
It now asks whether the current context contains enough files for a fix, and decides on that.
=> fix(autofix): Fix plan+code overpicking the simple path

src/seer/automation/autofix/components/coding/models.py, src/seer/automation/autofix/components/root_cause/models.py, src/seer/automation/autofix/evaluations.py, tests/automation/autofix/components/coding/test_coding_component.py, tests/automation/autofix/components/coding/test_coding_models.py, tests/automation/autofix/steps/test_root_cause_step.py, tests/automation/autofix/test_autofix_evaluations.py
This was causing a ValidationError: https://sentry.sentry.io/issues/6042731264/events/42fecd08b4184ba08e5922362e277dbd/?node=txn-78e04c51739044ee89bc3af57e3726f5&project=6178942&query=is:unresolved%20assigned_or_suggested:%5Bme,my_teams%5D&sort=date&statsPeriod=7d&stream_index=6
=> fix(autofix): Remove unit test from prompt model

DI.md
Zach's docs file only
Next step:
Use cloudy to manage this + put it in the develop docs ideally
=> feat(DI): DI docs md

docker-compose.yml, pyproject.toml
Should fix some mypy issue we were having
=> build(mypy): Adjust mypy options

src/seer/automation/autofix/steps/steps.py, tests/automation/autofix/steps/test_autofix_steps.py
=> chore(autofix): Nicer error message

.github/workflows/tests.yml, requirements-constraints.txt, requirements.txt, src/celery_app/config.py, src/seer/anomaly_detection/detectors/smoothers.py, src/seer/dependency_injection.py, src/seer/rpc.py, tests/conftest.py, tests/generators.py, tests/utils.py
Sets up vcrs for tests, and includes refactors to ci and our celery setup
=> feat(tests): RPC, DI refactors + VCRs in tests

src/seer/automation/agent/agent.py
This will prevent them from being logged to sentry.
=> fix(autofix): Raise AgentError for bad tool calls

src/seer/automation/autofix/autofix_agent.py, src/seer/automation/autofix/components/insight_sharing/component.py, src/seer/automation/autofix/components/insight_sharing/models.py
Custom prompting for each step type to get higher quality insight cards.
=> feat(autofix): Custom insight cards for each step

src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/coding/models.py, src/seer/automation/autofix/components/coding/prompts.py, src/seer/automation/autofix/steps/coding_step.py, src/seer/automation/autofix/tools.py, tests/automation/autofix/components/coding/test_coding_component.py
- Corrects the message types for the pre-filled memory files to be tool ones as llms will weigh them differently than simply assistant and user
- Modularized the prompt for root causes & user instructions
- Refactors and renames user instruction fields to be more clear to what they actually are.
Makes the fix score _slightly_ better on evals, now 0.5484 instead of  0.5360
=> fix(autofix): Coding agent prompt alignment

src/seer/automation/autofix/autofix_context.py, tests/automation/autofix/test_autofix_context.py
Handles issue #1527 and error https://sentry.sentry.io/issues/5806526572/
When we don't have access to one of the repos provided in the code mappings, we show the user the error message below:
=> fix(autofix): Show error if we can't access a repo

tests/seer/anomaly_detection/test_cleanup_tasks.py
- external alert ids were randomized between 1 - 100 so a collision could cause an alert to incorrectly be deleted resulting in a test failure
- required the `external_alert_id` to be passed in rather than randomized
=> fix(anomaly detection): Fix flaky test for cleaning disabled alerts

src/seer/automation/autofix/autofix_context.py, tests/automation/autofix/test_autofix_context.py
Fix the PR creation not saving the PR details. We need to actually save it to the db
=> fix(autofix): Fix PR creation not saving the pr details

src/seer/automation/autofix/steps/change_describer_step.py
When there are no codebase changes, we change the message displayed to the user to match.
Also adding a log there so that we can track these occurrences and investigate when and why this situation happens in the future.
=> chore(autofix): Update log when no fix is found

README.md, requirements-constraints.txt, requirements.txt, src/seer/automation/agent/client.py, src/seer/automation/agent/models.py, src/seer/automation/autofix/components/coding/prompts.py, src/seer/automation/autofix/components/root_cause/prompts.py, src/seer/automation/autofix/tools.py, tests/automation/agent/cassettes/test_gemini_generate_text_from_web_search.yaml, tests/automation/agent/test_client.py
Adds a tool to the Autofix agent that allows it to ask a question and receive an answer based on Google Search results, using Gemini 2.0 Flash.
This results in:
- a 19 second drop in total latency compared to the last eval ran on main (idk how reliable this is tho)
- a 1.5 point increase in "is root cause correct", now at 95%
- a 2 point increase in "is fixed:, now at 58%
=> feat(autofix): Add google search tool

src/seer/anomaly_detection/detectors/mp_scorers.py, tests/seer/anomaly_detection/detectors/test_mp_scorers.py, tests/seer/anomaly_detection/test_utils.py
This change limits the number of prophet inferences in batch detection mode to keep the store_data end point bounded. In this iteration we are limiting the location detection logic to just last 12 data points in the batch mode. In a follow-up we will also switch to invoking prophet just once for those 12 data points.
=> chore(anomaly detection): reduce prophet inference in batch mode to improve performance

src/seer/anomaly_detection/accessors.py
Removing multiple iterations on the time series and also pre-allocating lists. These changes result in about 15% reduction in time taken by the hydration method on local.
=> chore(anomaly_detection): optimization of hydration method

src/migrations/versions/3914e6cdb818_migration.py, src/seer/automation/codebase/models.py, src/seer/automation/codebase/repo_client.py, src/seer/automation/codegen/pr_review_coding_component.py, src/seer/automation/codegen/pr_review_publisher.py, src/seer/automation/codegen/tasks.py, tests/automation/codegen/test_pr_review.py, tests/automation/codegen/test_pr_review_publisher.py, tests/automation/test_steps.py, tests/test_celery.py
=> chore: Run pre-commit

src/seer/automation/autofix/components/root_cause/prompts.py, src/seer/automation/autofix/steps/coding_step.py
Confirmed that profiles are being sent to Autofix correctly. This PR just adds them to the prompt to make use of them.
=> feat(autofix): Add profiles to prompts

src/seer/automation/autofix/prompts.py
=> fix(autofix): Fix typo

src/seer/automation/agent/client.py
Resolves https://sentry.sentry.io/issues/6242199536/
=> fix(autofix): Null safety in gemini client

src/seer/utils.py, tests/automation/autofix/test_retry_stream.py
Make it easier to know when retrying was successful (log it) and when it wasn't (raise a separate exception)
=> chore(autofix) Log successful retries, separate retry exception

src/seer/anomaly_detection/detectors/mp_scorers.py
- Use a scaling factor for thresholds which applies to lower variance matrix profiles
=> chore(anomaly detection): Update IQR for lower variance MP

tests/automation/autofix/test_autofix_tasks.py
Skipping the tests that I have seen fail before. May not be comprehensive. Still no idea on the root cause.
=> fix(autofix): Skip tests causing seg faults

src/seer/automation/codebase/repo_client.py
=> Add logs for app credential flow

src/seer/app.py, src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/coding/models.py, src/seer/automation/autofix/components/coding/prompts.py, src/seer/automation/autofix/components/insight_sharing/component.py, src/seer/automation/autofix/components/root_cause/models.py, src/seer/automation/autofix/components/root_cause/prompts.py, src/seer/automation/autofix/components/solution/component.py, src/seer/automation/autofix/components/solution/models.py, src/seer/automation/autofix/components/solution/prompts.py, src/seer/automation/autofix/evaluations.py, src/seer/automation/autofix/event_manager.py, src/seer/automation/autofix/models.py, src/seer/automation/autofix/steps/coding_step.py, src/seer/automation/autofix/steps/root_cause_step.py, src/seer/automation/autofix/steps/solution_step.py, src/seer/automation/autofix/tasks.py, tests/automation/autofix/components/coding/test_coding_component.py, tests/automation/autofix/components/coding/test_coding_models.py, tests/automation/autofix/components/test_root_cause.py, tests/automation/autofix/steps/test_root_cause_step.py, tests/automation/autofix/test_autofix_evaluations.py, tests/automation/autofix/test_autofix_event_manager.py, tests/automation/autofix/test_autofix_tasks.py, tests/automation/autofix/test_models.py, tests/test_celery.py, tests/test_seer.py
Adds a Solution step that auto-runs after the Root Cause step and outputs a similar timeline. This is internally the same as the Plan part of the old Plan+Code. This also makes the Plan+Code step just Code.
The frontend PR should go in first.
=> feat(autofix): Refactor plan+code into a Solution step and a Code Changes step

src/seer/automation/autofix/components/root_cause/models.py, src/seer/automation/autofix/components/solution/models.py
Temporary fix to keep past runs working
=> fix(autofix): Allow any string in timeline

src/seer/automation/autofix/components/solution/prompts.py
=> chore(autofix): Prompt change for solution timeline

requirements.txt, src/seer/automation/autofix/components/root_cause/models.py, src/seer/automation/autofix/components/solution/models.py
deploys should be unblocked after this
=> fix(autofix): Make relevant code optional again with gemini sdk bump

src/seer/automation/agent/agent.py, src/seer/automation/agent/client.py, src/seer/automation/autofix/autofix_agent.py, src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/solution/component.py, src/seer/automation/codebase/repo_client.py, tests/automation/codebase/test_repo_client.py
Not going ahead with DeepClaude, but discovered some bug in converting tool calls between OpenAI, Anthropic, and Gemini, so fixing that. Also adding support for reasoning-related parameters for OpenAI.
Also improving the get_valid_file_paths check that the AI suggested.
And fixes the exception logging in get_file_content so we don't get spammed by Sentry.
And change the index at which we insert the initial prompt in the solution/coding step to prevent some hallucinations we were seeing.
=> fix(autofix): Some fixes

.github/workflows/validate-pipelines.yml
Missed one, my pr review tool found it
=> chore(ci): bump this one too

pyproject.toml, requirements-constraints.txt, requirements.txt, src/seer/automation/autofix/autofix_agent.py, src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/is_root_cause_obvious.py, src/seer/automation/autofix/components/root_cause/component.py
1. Langfuse SDK version bumped
2. Parallel threads will now log under the same langfuse trace
2. Adds the instruction to the root cause obvious call
=> feat(langfuse): Parallel traces in langfuse + obvious step instructions

src/seer/automation/codegen/pr_review_coding_component.py
Use claude-3-5-sonnet-v2@20241022
=> [Pr review step] Bump claude version 

.github/workflows/tests.yml, gocd/templates/bash/check-github.sh
=> ci: check for this specific job

src/seer/automation/autofix/components/root_cause/component.py
If `is_obvious` was True, we still ran the context gathering step, but the assistant message cleaning meant it just added a "." in the memory of the reasoning step. So we can just avoid calling the context gathering step at all in this case and save 5-10s.
=> fix(autofix): Remove extra gemini call in root cause step if obvious

src/seer/automation/autofix/components/comment_thread.py, src/seer/automation/autofix/components/solution/prompts.py, src/seer/automation/autofix/tasks.py
1. Updates solution timeline prompt to outline the sequence of changes needed.
2. Updates action detection in comment thread to work more as expected
Solution timelines look like this now, so much easier to read:
=> feat(autofix): Prompt updates

src/seer/automation/agent/client.py, src/seer/automation/autofix/event_manager.py, src/seer/automation/autofix/tasks.py, tests/automation/autofix/test_autofix_tasks.py
Changes the memory truncation logic when rethinking to preserve the memory up to the insight being re-thought. This makes it easier for users to comment on specific things and have Autofix iterate.
=> chore(autofix): Preserve more memory when rethinking

src/seer/automation/autofix/tools.py
=> chore(autofix): Prettier file search log

.github/workflows/linting.yml, src/seer/automation/autofix/tools.py
=> ci(lint): Re-enable CI Linting Autofixer! (no not that autofix)

src/seer/anomaly_detection/detectors/location_detectors.py, src/seer/anomaly_detection/detectors/mp_boxcox_scorer.py, src/seer/anomaly_detection/detectors/mp_scorers.py, src/seer/anomaly_detection/models/relative_location.py, tests/seer/anomaly_detection/detectors/test_boxcoxscorer.py, tests/seer/anomaly_detection/test_accessors.py
Adds timestamp to the threshold to make it easier to align the underlying timeseries with thresholds
=> Anomaly detection/threshold tweak

src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/coding/prompts.py, src/seer/automation/autofix/components/root_cause/component.py, src/seer/automation/autofix/components/solution/component.py, src/seer/automation/autofix/components/solution/prompts.py
If the coding output XML can't be parsed, ask the agent to fix it (up to one time).
Also update some prompts.
=> fix(autofix): Add retry for XML formatting in coding step

src/seer/automation/autofix/event_manager.py, src/seer/events.py
=> log(autofix): more autofix events

src/seer/automation/autofix/components/solution/models.py
=> fix(autofix): fix solution backwards compatibility

src/seer/automation/agent/embeddings.py, src/seer/automation/codegen/prompts.py, src/seer/automation/codegen/relevant_warnings_component.py
In an offline demo I got one of [these types of errors](https://sentry.sentry.io/issues/6279056251/?project=6178942). For now I think it's fine to just log and skip
=> fix(relevant warnings) Handle Gemini Nones, prompt tweaks

src/seer/automation/codegen/relevant_warnings_step.py
current code won't raise exceptions when submitting the request
=> fix(relevant warnings) Raise overwatch response for status

src/seer/anomaly_detection/tasks.py, tests/seer/anomaly_detection/test_cleanup_and_predict_tasks.py
- Fix validation issue upon adding new prophet entries
- Ensure current timestamp does not get overwritten
=> fix(anomaly detection): Prophet Validation Issue

src/seer/automation/autofix/event_manager.py, src/seer/automation/autofix/steps/change_describer_step.py, src/seer/automation/autofix/tasks.py, src/seer/events.py
Some new event types
1. Rethink w/ step key
2. Question Answer w/ step key
3. Coding Complete
4. Erroring now stores the step key
=> feat(autofix): Question answer, rethink, coding complete, and errored step

tests/automation/agent/test_client.py, tests/automation/agent/test_embeddings.py
=> Move embeddings tests

src/seer/anomaly_detection/models/algo_config.py, src/seer/anomaly_detection/tasks.py, tests/seer/anomaly_detection/test_cleanup_and_predict_tasks.py
Reducing it from from once every 12 hours to once every 24 hours.
=> chore(anomaly_detection): Reduce the frequency running prophet predictions

src/seer/json_api.py
- Creates tags for alerts if there is a validation error so understanding issues regarding this failure would be easier at scale
=> chore(anomaly detection): Tags for Alert ValidationError

src/seer/automation/agent/client.py
fix https://sentry.sentry.io/issues/6369703164/
=> fix(autofix) Retry Anthropic internal server error

src/seer/automation/codegen/relevant_warnings_component.py
there can be 1000s of warnings apparently
=> fix(relevant-warnings) Only log warnings with matches

src/seer/app.py, src/seer/automation/autofix/models.py, src/seer/automation/autofix/runs.py, tests/test_seer.py
A field in autofix state body to check repo access too
=> feat(autofix): Get state endpoint can check & update repo access

src/seer/automation/autofix/components/coding/component.py
Instead of rewriting the full file with gpt-4o-mini, we write a diff using claude sonnet 3.7. This keeps evals stable, but faster.
This removes all usage of OpenAI in production. However, OpenAI is still used in evals and in the unused replay summarization endpoint.
=> chore(autofix): Change coding apply model to claude with diff

src/seer/automation/agent/client.py, src/seer/automation/autofix/autofix_context.py, src/seer/automation/autofix/components/coding/component.py
If there is only one available repo, we autocorrect to that. Should alleviate some of our parsing errors in the coding step.
Also add some more errors to retry on in the LLM client.
=> fix(autofix): Stronger autocorrect for repo names

src/seer/automation/codegen/relevant_warnings_component.py
still dogfooding, so not too costly
=> fix(relevant-warnings) Upgrade relevancy prediction to flash

src/seer/automation/models.py
Make tag value optional to prevent validation error from events with "processing error"
=> fix(issue summary): Allow None tag values

src/seer/automation/codebase/repo_client.py
pulls because it's a `PaginatedList` it evaluates to true when empty....
=> fix(autofix): Fix PR paginated list schenanigans

src/seer/automation/autofix/components/confidence.py, src/seer/automation/autofix/event_manager.py, src/seer/automation/autofix/models.py, tests/automation/autofix/test_autofix_event_manager.py
- Mark root cause starts whether autorun and with the autorun source
- Mark solution runs with unit tests
- Mark solution runs with a new step
- Mark solution runs with a step removed
- Log on confidence question
=> feat(autofix): Autorun & more analytics improvements

requirements-constraints.txt, requirements.txt, src/seer/anomaly_detection/anomaly_detection.py, src/seer/app.py, tests/test_seer.py
- Add datadog to seer
- For now, add metrics to anomaly detection endpoints and seer health and readiness check
https://docs.datadoghq.com/metrics/custom_metrics/dogstatsd_metrics_submission/
=> chore(seer): Add datadog to seer app

src/seer/app.py, src/seer/workflows/compare/models.py, src/seer/workflows/compare/processor.py, src/seer/workflows/compare/scorer.py, src/seer/workflows/compare/service.py, tests/workflows/test_data/test_payload_0.json, tests/workflows/test_processor.py, tests/workflows/test_scorer.py, tests/workflows/test_service.py
1. Add referrer field to the request
2. Fix Laplace smoothing to the correct version
3. Rename functions to snake_case
=> ref(workflows): fixes for v1

src/seer/app.py
- Init datadog and connect to port with the relevant envs
=> chore(seer): Init datadog

src/seer/app.py
- Attempts to fix datadog from https://github.com/getsentry/sentry/pull/68644/files# so the agent can receive metrics
=> chore(seer): Fix datadog init

src/seer/automation/codegen/prompts.py
10 words is not descriptive enough, expanding it to at most 20 words
=> fix(relevant-warnings): Increase description word limit to 20

src/seer/anomaly_detection/accessors.py, src/seer/anomaly_detection/anomaly_detection.py, src/seer/anomaly_detection/detectors/anomaly_detectors.py, src/seer/anomaly_detection/detectors/anomaly_scorer.py, src/seer/anomaly_detection/detectors/mp_scorers.py, src/seer/anomaly_detection/models/__init__.py, src/seer/anomaly_detection/models/timeseries_anomalies.py, tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py, tests/seer/anomaly_detection/detectors/test_anomaly_scorer.py, tests/seer/anomaly_detection/models/test_timeseries.py, tests/seer/anomaly_detection/models/test_timeseries_anomalies.py, tests/seer/anomaly_detection/test_accessors.py, tests/seer/anomaly_detection/test_anomaly_detection.py, tests/seer/anomaly_detection/test_cleanup_and_predict_tasks.py
- Surfaces algorithm type used for alerting to ease debugging of customer feedback
- Currently not used directly
=> chore(anomaly detection): Surface algorithm type used to alert

src/seer/anomaly_detection/anomaly_detection.py, src/seer/anomaly_detection/detectors/anomaly_detectors.py, src/seer/anomaly_detection/detectors/anomaly_scorer.py
- Correctly appends the proper flag for the `combined_original_flag`
- Fixed some small typos too in comment/log
=> fix(anomaly detection): Fix Appending new flag

.vscode/extensions.json
- Based on [Sentry's extension file](https://github.com/getsentry/sentry/blob/master/.vscode/extensions.json)
- Added the minimum extensions I thought would be good
=> chore(seer): Add Recommended Extensions

src/seer/automation/codegen/prompts.py
Attempt to fix `Error generating pr review for ...: Invalid JSON format inside <comments>`:
Checked Langfuse and saw that the output was not comma separating json responses so explicitly prompt to avoid this.
=> Update PR review prompt

src/seer/bootup.py
depends on https://github.com/getsentry/ops/pull/14607
=> chore(seer): add sentry region to sdk

src/seer/automation/agent/embeddings.py, tests/automation/agent/test_embeddings.py
same interface as sentence-transformers
=> Allow single str Google embeddings input

src/seer/anomaly_detection/accessors.py, tests/seer/anomaly_detection/test_accessors.py
- Store values in 60d history prior to deleting to ensure data for debugging
- When users change alert type from dynamic to something else, the alert data is deleted so can be difficult to debug why they deleted the alert in the first place even with feedback
=> chore(anomaly detection): Store history prior to delete

src/seer/json_api.py
- log the raw request for validation errors to help debug further
=> Log request body if error

src/seer/automation/models.py
Adds the following sections from issue details to the initial context:
- Message
- Stacktrace (non-exception ones)
- HTTP Request
Seems to bump evals slightly.
=> feat(autofix): Add more context

tests/automation/autofix/test_autofix_tasks.py
works fine consistently locally....let's skip...
=> fix(ci): skip coding test

src/seer/automation/agent/embeddings.py, src/seer/utils.py, tests/automation/agent/test_embeddings.py
=> Embeddings progress bar

src/seer/automation/autofix/components/root_cause/models.py, src/seer/automation/autofix/event_manager.py, src/seer/automation/autofix/models.py, src/seer/automation/autofix/steps/coding_step.py, tests/automation/autofix/test_autofix_event_manager.py
Saves the last memory message as a `termination_reason` if there were no code changes.
=> feat(autofix): Save explanation if no code changes

Dockerfile, Lightweight.Dockerfile, requirements-constraints.txt, requirements.txt
We had some lunar calendar and astronomical libraries (???) that weren't building.
=> fix(ci): Remove unnecessary dependencies and reorganize dockerfiles

src/seer/automation/summarize/issue.py
There are fewer "fixable" issues in prod than in the test set. Lowering the threshold a bit to account for this
=> fix(fixability) Lower thresh a bit

src/seer/automation/codegen/relevant_warnings_step.py, tests/automation/codegen/test_relevant_warnings.py
Seer to send info to Overwatch. https://github.com/codecov/overwatch/issues/98
=> feat(relevant-warnings) Send diagnostics to Overwatch

src/seer/automation/codebase/models.py, src/seer/automation/codegen/prompts.py, src/seer/automation/codegen/relevant_warnings_component.py, tests/automation/codegen/test_relevant_warnings.py
The current analysis/thinking added in #2423 is shallow and doesn't say much. Also hoping to reduce noise
=> fix(relevant-warnings) More instructions on analysis

src/seer/severity/severity_inference.py
=> feat(severity): Add thread-count tag

Dockerfile
Fixes the main dockerfile not copying this sh file in
=> fix(build): Fix no flower.sh in prod

src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/steps/steps.py, src/seer/automation/summarize/issue.py
Forgot to check if the step is active when deciding whether or not to add unit tests. Also fixing an incorrect Sentry tag.
=> fix(autofix): correct has_test condition

src/seer/automation/autofix/steps/coding_step.py, src/seer/automation/autofix/steps/root_cause_step.py, src/seer/automation/autofix/steps/solution_step.py, src/seer/automation/autofix/steps/steps.py, src/seer/automation/autofix/tasks.py
Fix how some tags are set, add more tags
=> chore(autofix): More sentry instrumentation

src/seer/automation/autofix/steps/change_describer_step.py, src/seer/automation/autofix/steps/coding_step.py, src/seer/automation/autofix/steps/root_cause_step.py, src/seer/automation/autofix/steps/solution_step.py, src/seer/automation/autofix/tasks.py
Merge this once https://github.com/getsentry/ops/pull/15117 has been deployed
=> fix(autofix): Set acks_late on core autofix tasks

src/seer/automation/codebase/repo_client.py
Some soft kills are caused by our GH client retrying a 403 from the get_repo metadata request, which lines up w/ [the behavior in the docs](https://pygithub.readthedocs.io/en/v2.1.0/github_objects/GithubRetry.html). We might get a better error message out if we let retries fail and re-raise the 403
=> fix(autofix): Don't retry longer than soft kill

Dockerfile, tests/test_ripgrep_search.py
Forgot to include it in the main dockerfile too. Adding a test to make sure it exists.
=> fix(autofix): Add ripgrep to the other dockerfile too

gocd/templates/bash/run-migrations.sh
Remove hardcoded ST using seer gpu
=> ci(migrations): Use seer instead of seer-gpu for ST migrations

src/seer/automation/codebase/repo_client.py, tests/automation/codebase/test_repo_client.py
Add logging to get more debugging evidence.
=> log(autofix): Add logging for when repos are large

src/seer/automation/codebase/repo_client.py, tests/automation/codebase/test_repo_client.py
=> Revert "log(autofix): Add logging for when repos are large"

src/seer/automation/autofix/components/root_cause/component.py, src/seer/automation/autofix/components/solution/component.py
2.5 flash is not available in de. This falls back to 2.0 flash in that case.
=> fix(autofix): Fallback to gemini 2.0 flash in de

.github/workflows/relevant-warnings.yml, src/seer/automation/codegen/relevant_warnings_step.py
Adjust the relevant-warnings dogfooding to use outputs from both ruff and mypy (instead of ruff only)
=> feat(relevant-warnings): Add mypy to gha

src/seer/automation/codebase/repo_manager.py, tests/automation/codebase/test_repo_manager.py
=> fix(autofix): Fix RepoManager errors not being grouped

src/seer/automation/assisted_query/assisted_query.py, src/seer/automation/assisted_query/create_cache.py
- Getting some slowdowns in projects with lots of attributes and values
- Adding logs to test hypothesis and make debugging clearer
- Will remove/reduce logs as issue is fixed
=> chore(trace queries): Add logs

src/seer/anomaly_detection/anomaly_detection.py
Since we still have some situations when batch detection takes about 8 seconds, the Frontend has increased the time allocation to 10 seconds.
=> chore(anomaly-detection): Match time budget for store data end point to changed sla

src/seer/automation/codegen/evals/datasets.py
breaks up the runs further down into "positive" (where we expect bugs) and "negatives" (where we don't expect bugs) items and calculate metrics based on those.
Also  drops the "noise" metric (number of suggestions not matched) which is not super relevant at this point and it's not standarized (so avg is not very good) in favor of "suggestions" that were sent.
Looks like this:
```
==========================================
Run 3rd-full-run
==========================================
Total items: 47
┌────────────────────────┬───────┬────────────┐
│ Metric                 │ Count │ Percentage │
├────────────────────────┼───────┼────────────┤
│ Evaluated successfully │    41 │     87.23% │
│ Evaluated with errors  │     6 │     12.77% │
└────────────────────────┴───────┴────────────┘ …
```
=> improve stats from run reports

tests/automation/codebase/test_repo_manager.py
Thought these would be nice originally, turns out they're really flaky for some reason. So let's remove cuz they're nonessential.
=> tests(autofix): Remove flaky logger testing

.github/workflows/linting.yml, .github/workflows/tests.yml, .github/workflows/validate-pipelines.yml
This is for merge queue to work
=> ci(seer): Trigger workflows on merge_group

.github/workflows/tests.yml
align the event name with the condition for model loading, and swap the condition
=> ci(merge-queue): Swap this condition

src/seer/automation/codebase/repo_manager.py, tests/automation/codebase/test_repo_manager.py
Use multithreading to download the GCS archive in chunks, locally it proved to be faster, let's see when deployed.
=> feat(repo-manager): Multithreaded gcs downloads

src/seer/automation/agent/client.py
=> fix(autofix): Disable global endpoint for flash 2.5

src/seer/automation/autofix/event_manager.py, tests/automation/autofix/test_autofix_event_manager.py
Remove the crossed-out repro test from the solution result
=> chore(autofix): Remove test from solution plan default

.github/workflows/linting.yml
Name this job so we can make rules on it
=> ci: Name the linting job

src/seer/automation/agent/client.py
All anthropic calls, both in DE and US, will be routed to Europe west 4 for PT.
=> chore(automation): Switch anthropic to europe west 4

src/seer/automation/codegen/unit_test_coding_component.py, tests/automation/codegen/test_unit_test_coding_component.py
Fixes Sentry error: 
https://sentry.sentry.io/issues/6602910131/?project=6178942&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=1
=> [fix] Fix unit test coding component repo client type

src/seer/automation/assisted_query/create_cache.py, tests/automation/assisted_query/test_create_cache.py
- Add langfuse tracing to cache creation
**Question**: Should I be more granular here or should this generally be enough?
=> chore(assisted query): Update Langfuse tracing 

src/seer/automation/agent/client.py
- Add tracing to specific cache creation to capture prompt
=> chore(assisted query): Trace Cached Prompt

src/seer/automation/codegen/pr_review_coding_component.py
right now we're trying to run 3.5 in a region not supported (since we moved to PT)
=> fix(seer): bump pr review to sonnet 3-7 (to use PT)

src/seer/automation/autofix/runs.py
According to several profiles captured in Sentry, this method would slow down both the get endpoint and the start endpoint by 3-11 seconds. This occurred when there were many repositories being processed. This PR simply parallelize the slow repo client operations if there are multiple repositories to update.
=> chore(autofix): Parallelize update_repo_access_and_properties

src/seer/automation/agent/client.py
Return thoughts as part of gemini stream for better UX
=> chore(autofix): Include gemini's thoughts in content stream

src/seer/automation/autofix/steps/coding_step.py, src/seer/automation/autofix/steps/root_cause_step.py, src/seer/automation/autofix/steps/solution_step.py, src/seer/automation/autofix/steps/steps.py, src/seer/automation/autofix/tasks.py
Probably minimal impact but should do it anyway
=> chore(autofix): Remove some unnecessary db reads

src/seer/automation/codebase/tasks.py
This will make it delete existing backfill jobs and run backfill again, for debugging purposes.
=> debug(autofix): Make repo backfill run repeatedly for these projects

src/seer/automation/codebase/tasks.py
There could be backfill jobs that don't have an archive (failed) so this basically just makes sure they're cleaned out before attempting to create one
Again, for the sake of development...if repo caching is all good then we can go to actually implement this backfill correctly...
=> fix(repo-backfill): There could be backfill jobs without archives

src/seer/automation/autofix/autofix_agent.py
We were rejecting all tool calls by mistake
=> fix(autofix): Fix duplicate tool logic

src/seer/app.py, src/seer/automation/assisted_query/assisted_query.py, src/seer/automation/assisted_query/models.py, src/seer/automation/assisted_query/prompts.py, tests/automation/assisted_query/test_assisted_query.py
- Workflow returns multiple options for the user to select
- Returns in a list
- Updated prompts
- Please merge after: [#91916](https://github.com/getsentry/sentry/pull/91916)
=> chore(trace-queries): Support multiple options

src/seer/automation/autofix/components/root_cause/component.py, src/seer/automation/autofix/components/root_cause/prompts.py, src/seer/automation/autofix/components/solution/component.py, src/seer/automation/autofix/components/solution/prompts.py, src/seer/automation/autofix/prompts.py, src/seer/automation/autofix/tools/tools.py, tests/automation/autofix/test_autofix_event_manager.py
Much more robust prompts and a solution architecture that is just 1 step using gemini 2.5 pro instead of flash + claude 3.7. Also bumping the 2.5 flash preview checkpoint. 
Root cause ~87%
Solution ~62%
(so stable, or at least a return to form)
& Faster run time
=> feat(autofix): Prompt engineering and new solution architecture

src/seer/automation/autofix/evaluations.py, src/seer/automation/autofix/steps/coding_step.py, src/seer/automation/autofix/steps/root_cause_step.py, src/seer/automation/autofix/steps/solution_step.py, src/seer/automation/models.py, src/seer/automation/summarize/issue.py, tests/automation/summarize/test_issue.py
Adds span evidence model on autofix and issue summary. Should allow us to operate on most performance issues. 
Follow ups:
- Test in prod with `yarn dev-ui`
- Enable UI on frontend
- Enable automation
=> feat(autofix): Receive span evidence from issues

.cursor/rules/tests.mdc
These cursorrules allow the cursor agent to automatically run tests correctly in seer by itself
=> meta: cursorrules for tests

src/seer/automation/autofix/components/root_cause/component.py, src/seer/automation/autofix/components/solution/component.py
It was like a 2% dip in evals. I guess fine for now. 
I'm assuming all the region configs are already correct. It works locally ofc.
=> chore(autofix): Switch to april checkpoint for gemini 2.5 flash

src/seer/automation/codegen/bug_prediction_component.py, src/seer/automation/codegen/prompts.py
these steps require some intelligence. should update to almost-latest models
=> fix(bug-prediction): Bump formatter and hypotheses structure models

src/seer/automation/codebase/repo_manager.py, tests/automation/codebase/test_repo_manager.py
Refactors Repo Manager to keep download the github repo tar again
=> feat(autofix): Repo manager downloads tar from gh

src/seer/automation/autofixability.py, src/seer/grouping/grouping.py, src/seer/severity/severity_inference.py
tad annoying to see these locally
=> chore: Silence progress bars in sentence transformer calls

src/seer/automation/autofix/runs.py
In some cases with many repos where a branch name is provided, validate branches could add up to 8 seconds of cold start based on some profiles. Parallelizing it when there are multiple repos should help.
=> chore(autofix): parallelize repo branch validation

src/seer/automation/summarize/issue.py
we trace this call in sentry, and store scores in both seer `issue_summary` and sentry `sentry_groupedmessage`, so scores are easy to get.
looking at profiles, the langfuse call can add up to 150ms latency for an op that takes 10-20ms.
=> chore(fixability): Disable langfuse

README.md
Update some seer setup sections
+ new autofix setup section
=> chore(readme): Small readme updates

src/seer/automation/codebase/repo_client.py
exploring feasibility of reading code context for issue summary
=> chore(automation): Trace repo_client init

src/seer/automation/agent/client.py, src/seer/automation/autofix/components/coding/component.py, src/seer/automation/autofix/components/root_cause/component.py, src/seer/automation/autofix/components/solution/component.py, tests/automation/agent/test_client.py
Provide lists of models to fallback to for Autofix use cases, upgrade to Claude Sonnet 4, and use our Sonnet 4 PT with good fallbacks
=> feat(autofix): Model fallbacking + sonnet 4

src/seer/automation/codebase/repo_manager.py
Only make one log for removed files instead of one for every single file
=> chore(repo manager): Cleaner logs
