- .github/workflows/test-app.yml
- Dockerfile
- cloudbuild.yaml
- models/.gitignore
* This creates an empty `models` directory, where model data will eventually go during builds. The `.gitignore` in there is a bit of a hack; Git doesn't add empty directories, but a no-op .gitignore makes the directory not-empty.
* It sets up the GitHub Actions build to fetch files from the designated bucket and copy them into the `models` directory; for this, it uses a GCP service account created for this and limited to the bucket in question
* It sets up the Cloud Build config to fetch files from the designated bucket and copy them into the `models` directory; for this, it uses the default service account for Cloud Build, which will have access to the bucket in question
* It tells the Dockerfile to copy the contents of the `models` directory in this repo into its own `models` directory. …
> (OPS-3797) Set up model retrieval for GHA and Cloud Build

- cloudbuild.yaml
#83 successfully added the `gsutil cp` command to `cloudbuild.yaml`, so Cloud Build was able to start copying files. However, I forgot the `-r` flag, which is necessary to recurse through the subdirectories. (D'oh!)
> fix(cloudbuild): Add recursive flag to cp

- .github/workflows/test-app.yml
- src/seer/trend_detection/trend_detector.py
- removed the docker build step from the github test suite (causing failures due to it running out of storage)
- fixed the midpoint fallback logic
- allow breakpoints at the very end of a timeseries
> fix: Fix midpoint fallback, update start/end logic, remove docker build

- src/seer/seer.py
- src/seer/trend_detection/trend_detector.py
- black format trend_detector.py
- add `min_ms_change` parameter with a default value of 25 (miliseconds)
- remove unused `zerofilled` parameter
- make variable names more readable
- remove duplication of default value logic
@udameli @Zylphrex lmk what you guys think makes sense for a default value for `min_ms_change`. Also, we may want to set it to a lower value or remove it for trends so stuff like this still shows up
> feat: add minimum ms parameter

- src/seer/grouping/grouping.py
return an empty SimilarityResponse if there are no neighbors, rather than throwing an index out of bounds error
> fix(grouping): check if there are any valid similarity responses

- pyproject.toml
- requirements.txt
- src/seer/automation/autofix/agent_context.py
Turns out the github compare API [returns a maximum of 300 files ](https://stackoverflow.com/a/71447308), breaking our code to embed the diff between the cached commit and the commit in the autofix request.
Use the git diff API endpoint as the above stackoverflow post suggests which appears to return all file diffs (confirmed with a 1k file++ test run). We have to extract the git authorization headers from the PyGithub library and parse the diff locally. We also fix the issue with not correctly handling removed files.
> fix(autofix): Fix Github diff truncated files list when embedding for autofix

- src/seer/automation/autofix/agent_context.py
1. The index was not being correctly loaded because llama_index for some reason was saving the vector store to `default__vector_store.json` when the correct directory is `vector_store.json`? 
2. We were not caching the new index at the new commit
1. Explicitly loading a `MemoryVectorStore` seems to fix this.
2. We are now caching the new index and the commit sha at this point into the local filesystem.
3. Instrument how long it takes to load the index
> fix(autofix): Fix the vector store index not correctly being loaded + now save the latest index

- src/celery_app/app.py
Weren't getting any sentry errors even though there were errors within the worker. Uses same DSN as the normal seer.
> chore: Add sentry sdk to celery worker

- src/seer/rpc.py
Response could just be None from the rpc endpoint thus it was throwing an error in gcp logs
> fix(rpc): Only return json rpc response when it actually is a json

- Dockerfile
- celeryworker.sh
- src/celery_app/app.py
- src/seer/automation/autofix/agent_context.py
- src/seer/automation/autofix/autofix.py
1. Turns out the celery process runs as many workers as the number of available CPU cores. This means there will be concurrent processes.
2. The embedding files are not locked
3. We aren't also correctly removing the temp directory if the pipeline short circuited or errored.
4. We were logging debug logs from various libraries as well because of the blanket log level debug setting
1. Set max concurrency on the celery process to 4 workers
2. Lock the embedding files throughout the whole data loading process.
- The files will be locked for the entire process of loading data; that means only one worker at a time can go through the data loading process which is a bottleneck. However, this should be a temporary compromise during PoC stage to ensure that only the latest commit's embeddings are …
> fix(autofix): Acquire file locks when embedding repos

- src/seer/automation/autofix/agent_context.py
- src/seer/automation/autofix/utils.py
If the second commit in a git diff is in the past it returns an empty diff; the functionality we need is essentially to be able to turn the repo from one state to another. To accomplish this we implement an arbitrary "reverse diff" where the added files are now removed files, and the modified/deleted files become the changed files.
This PR also includes improvements to logging.
Tested locally
> fix(autofix): Support reverse git diffs

- src/seer/automation/autofix/event_manager.py
make it consistent with how the other steps are presented
another option, @jennmueng i'll leave this up to you, we split this into two steps on the UI:
1. `Generating Execution Plan` (which is just a standalone step, similar to codebase indexing)
2. `Execution Plan` which populates with the actual plan after the above step finishes
^ is maybe a little bit more digestable but no strong feelings
> chore(ai-autofix): update label for execution plan

- src/celery_app/tasks.py
- src/seer/app.py
- src/seer/automation/autofix/autofix.py
- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/codebase_context.py
- src/seer/automation/autofix/context_manager.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/prompts.py
- src/seer/automation/autofix/repo_client.py
- src/seer/automation/autofix/tools.py
- src/seer/automation/autofix/utils.py
- tests/automation/autofix/test_autofix.py
- tests/automation/autofix/test_context_manager.py
Will short circuit and skip codebase index update step if the files in the stacktrace do not match the ones that changed since the last commit diff. This logic is part of the new codebase context overhaul to pgvector we are doing but this is done in advance in anticipation of higher volume on Monday.
Includes a lot of refactoring cleanup too + unit tests for the short circuiting!
Tested e2e with local Sentry App
> feat(ai-autofix): Short circuit the diff embedding step with stacktrace files

- requirements.txt
- src/seer/app.py
- src/seer/grouping/grouping.py
- src/seer/schemas/seer.py
- src/seer/schemas/seer_api.json
- expect additional `project_id` parameter
- use `project_id` to identify which embeddings cache to reference
- backend model changed to https://huggingface.co/jinaai/jina-embeddings-v2-base-code
updated code for indexing [here](https://github.com/getsentry/ml-models/blob/main/grouping/grouping_artifacts.ipynb)
note - there are some schema changes unrelated to my PR, which reflect prior changes that @jennmueng made to autofix (the `generate_schemas` script just hadnt been run since then)
> feat(grouping): enable multi-project grouping support

- gocd/pipelines/seer.yaml
https://deploy.getsentry.net/go/tab/build/detail/deploy-timeseries-analysis-service/89/deploy/1/run-migrations
Was hoping the gocd validation would have caught this, but it's an easy fix.
> Fixing gocd pipeline definition

- src/seer/generator.py
- tests/conftest.py
- tests/test_generator.py
Adds a property test based framework.
Add tests with type annotations, decorate with `@generate`, then have your test run with random inputs based on the types!  Make assertions into invariants about inputs without having to create fake inputs.
You can guide the generation process with arbitrary functions and with `Examples` annotations as well.
Will be using this in my async PR that follows up.
> Adds property based testing library

- Dockerfile
- requirements.txt
- src/celery_app/app.py
- src/seer/app.py
- src/seer/bootup.py
- src/seer/db.py
- src/seer/generator.py
- src/seer/tasks.py
- tests/conftest.py
- tests/test_tasks.py
Cleaning up mypy and some failing tests (minor).  This is the starting place.
Next step will be integrating, slowly, the existing work of @jennmueng to make use of the async background process.
This framework supports a few things.
1.  Optional durable work queueing.  For work that should be retried indefinitely until it works, but coalesced so that multiple requests to do the work become one unit of that work (indexing).
2.  Ability to schedule work into an async processor from any context.  This can be remote (schedule work to be processed by any worker, durability preferred) or local (schedule work to be processed on this pod, latency preferred).
3.  Ability to even put GPU or CPU work off the celery queue.
Follow up will include using shared memory so that python services don't all …
> Adding tasks framework for background processing

- src/seer/automation/autofix/autofix.py
- src/seer/automation/autofix/prompts.py
The execution agent context retriever often returned a response that was invalid for the json parser and was extremely flaky.
- Have it return a json array inside a clear xml tag for ease of parsing. This way we specifically are able to extract it and ignore noise the llm says
- Provide multi-shot examples for the prompt for better queries + semantic queries.
> fix(autofix): Fix execution agent context retriever

- src/seer/automation/autofix/autofix.py
- tests/conftest.py
Let's agree on:
- v0 (the original POC)
- v1 (this current version)
- v_n ....
> ref(langsmith): Disable langsmith in tests + label autofix chain as v1

- src/seer/automation/autofix/models.py
- tests/automation/autofix/test_models.py
Forgot to reverse the stacktrace before truncating it.....we were using the first 4 most irrelevant frames the whole time...
- Correctly reverses
- Default truncates to 16
> fix(ai-autofix): Fix stacktrace to_str logic

- .github/workflows/commit-schemas.yml
Small adjustment so that PRs aren't updating our official json schemas, only master merged work is.
> Only commit schema changes from master

- src/seer/automation/autofix/autofix.py
- src/seer/automation/autofix/event_manager.py
Re-organize the event steps as we were hitting an error where the plan step didn't exist in the `next(...`
> fix(autofix): Fix planning step event not existing

- Dockerfile
- Makefile
- docker-compose.cuda.yml
- requirements.txt
Running `make dev-cuda` will run docker-compose with gpus enabled
> build: Use cuda-supported docker image

- src/seer/automation/autofix/models.py
- src/seer/automation/codebase/repo_client.py
- tests/automation/codebase/test_repo_client.py
Sentry side repo providers come in the format `integrations:github` etc
Fixes [TIMESERIES-ANALYSIS-SERVICE-2N](https://sentry.sentry.io/issues/5028696400/)
> fix(ai-autofix): Accept git repo provider format from sentry

- src/seer/automation/autofix/models.py
- tests/automation/autofix/test_models.py
Validate that there are no duplicate repository definitions in a request. Duplicates will be pruned on the sentry side.
> fix(ai-autofix): Validate duplicate repos in autofix request

- src/seer/automation/codebase/codebase_index.py
We reverted to 1 when we were cpu/memory constrained, now we aren't
(4 worked well on L4 in my experiments)
> chore(autofix): Revert the embedding batch size to 4

- src/seer/automation/autofix/autofix.py
- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/models.py
- src/seer/automation/codebase/parser.py
- src/seer/automation/codebase/utils.py
- tests/automation/codebase/test_parser.py
Attempts to fix [TIMESERIES-ANALYSIS-SERVICE-2S](https://sentry.sentry.io/issues/5029600041/)
Refactors the document chunk models to not need a `repo_id` in the base model (now renamed `BaseDocumentChunk`) while ones with embeddings are now `EmbeddedDocumentChunk` and the one that has been retrieved from db is `StoredDocumentChunk`.
This way it is clearer that you're working with `StoredDocumentChunk` when retrieving from the database and the former two models are transitional and only used when processing chunks.
> ref(ai-autofix): Better design for document chunk models

- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/repo_client.py
- tests/automation/codebase/test_repo_client.py
Sentry's provider values come in as `integrations:github` etc
> fix(autofix): Fix repo provider name for repo info query

- src/seer/automation/autofix/models.py
- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/repo_client.py
- tests/automation/autofix/test_models.py
- tests/automation/codebase/test_repo_client.py
Move repo validation logic to where it should be, so we don't get any leftover unprocessed repo provider values
> ref(autofix): Move repo provider processing + validation logic to model

- src/seer/automation/autofix/autofix.py
- src/seer/automation/codebase/codebase_index.py
- tests/automation/codebase/test_codebase_index.py
Resolves [TIMESERIES-ANALYSIS-SERVICE-35](https://sentry.sentry.io/issues/5037525890/)
Introduces logic to correctly remove chunks that no longer exist in a document, embed only the new chunks, and update the indices of neighboring chunks during the codebase indexing step. All done by chunk hash comparison.
- Adds unit tests to test the update/delete cases
- Adds span instrumentation to chunking and embedding steps in both codebase index creation and update
> fix(autofix): Fix codebase index updating logic

- pyproject.toml
- requirements.txt
- src/seer/automation/autofix/autofix.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/tools.py
- src/seer/automation/codebase/ast.py
- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/parser.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/models.py
- tests/automation/autofix/test_autofix_tools.py
- tests/automation/codebase/test_codebase_index.py
- tests/automation/codebase/test_parser.py
Computes a diff of the combined file changes of an autofix run. Does not use the github API, this way we can use this to generate a diff for a set of file changes without needing to interact with github at all.
In conjunction with https://github.com/getsentry/sentry/pull/66522
> feat(autofix): Output a diff with autofix result

- src/seer/automation/autofix/tasks.py
`model_dump` will serialize the sub fields which we don't want here, use `dict(model)` instead to pass the fields without serializing them: https://docs.pydantic.dev/latest/concepts/serialization/#dictmodel-and-iteration
`model_copy(update=...` does not validate/re-instantiate the fields passed to it
> fix(autofix): Use dict instead of model_dump when fetching state

- src/seer/automation/autofix/autofix.py
- src/seer/automation/autofix/components/assessment/component.py
- src/seer/automation/autofix/components/executor/component.py
- src/seer/automation/autofix/components/planner/component.py
- src/seer/automation/autofix/models.py
- tests/automation/autofix/test_models.py
Includes the variables from the stacktrace frame in the components:
- Preliminary Assessment
- Planning
- Executor
This would allow autofix to create fixes with much better understanding of the data flowing through when the error occurred.
Also updates the versioning of the components affected by the new stackframe vars to v1.2
[Example langsmith run with these changes](https://smith.langchain.com/public/f246289e-f305-4c05-b545-beeb8bd14ad5/r)
> feat(autofix): Include stacktrace frame variables

- src/seer/automation/autofix/tools.py
- tests/automation/autofix/test_autofix_tools.py
Tried on 2 issues locally, no more unexpected newlines introduced:
https://github.com/getsentry/seer/pull/418/files
https://github.com/getsentry/seer/pull/416/files
Issue was caused by the LLM getting confused with the extra newline in the XML tag contents, so it often added one. This fix ensures that there is no newline padding in the input to the LLM and only adds the newline after and ensures both the reference and replacement snippet end in a newline.
> fix(autofix): Fix replacements introducing newlines

- requirements.txt
- src/seer/automation/agent/agent.py
- src/seer/automation/agent/client.py
- src/seer/automation/autofix/autofix.py
- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/components/assessment/component.py
- src/seer/automation/autofix/components/reranker/component.py
- src/seer/automation/autofix/components/reranker/models.py
- src/seer/automation/autofix/components/reranker/prompts.py
- src/seer/automation/autofix/components/retriever.py
- src/seer/automation/autofix/components/retriever_with_reranker.py
- src/seer/automation/autofix/tools.py
- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/models.py
- src/seer/automation/component.py
- src/seer/automation/models.py
Introduces an LLM reranker step to our semantic codebase search.
It's also the first usage of `pydantic-xml` which allows us to easily parse from and convert to the XML format we use in our prompts.
> feat(autofix): Introduce retrieval reranker

- .envrc
This removes the `deactivate` call from `.envrc`, similar to what was done in https://github.com/getsentry/sentry/pull/67827. Two reasons for this:
- In VSCode it can cause an infinite loop, where `direnv` calls our `.envrc`, our `.envrc` calls `deactivate`, that call gets routed to the VSCode Python extension's `deactivate` script, that script runs the normal `deactivate` stuff but then also cals `zsh`, which loads your `.zshrc`, which includes the code activating `direnv`, which then causes it to call our `.envrc`, which calls `deactivate`... You get the idea. Nothing good comes of it.
- The `deactivate` code (a non-`zsh`-calling copy of it which lives in the standard virtual env `activate` script) is called as the first act of `activate` in any case, so our call to it is redundant. …
> chore(dev): Stop calling `deactivate` in `.envrc`

- celeryworker.sh
- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/utils.py
- src/seer/grouping/grouping.py
Assign one Cuda device to one celery process. Tested on I4 VM. Below are screen shots of memory and GPU usage when I submitted 100 autofix requests to Seer.
>Baseline - Memory and CPU before submitting 100 requests
>Snapshot 1 during processing
>Snapshot 2 during processing
>Snapshot 3 during processing (memory drops after completion of a batch)
>After 100 requests -  memory back to baseline
> chore: Use all CUDA devices

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/repo_client.py
Codebase index loading was skipped for PR creation, so we move the repo client initialization out because that's all we need for PR creation
> fix(autofix): Initialize a repoclient for creating PRs

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/components/retriever.py
- src/seer/automation/autofix/components/retriever_with_reranker.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/pipelines.py
- src/seer/automation/autofix/tasks.py
- src/seer/automation/autofix/tools.py
- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/namespace.py
- src/seer/automation/pipeline.py
- tests/automation/autofix/test_pipelines.py
This adds a codebase indexing step in the root cause analysis until we separately call it from the frontend with the new onboarding.
Originally this was to be temporary but I realise having this check isn't too bad an idea
> feat(autofix): Call create codebase index if any repos are missing from a run

- src/seer/automation/codebase/namespace.py
- tests/automation/codebase/test_namespace.py
Fixes [SEER-48](https://sentry.sentry.io/issues/5226499519/)
> fix(autofix): Create or get namespace instead of strict create

- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/models.py
- src/seer/automation/codebase/namespace.py
- tests/automation/codebase/test_namespace.py
The db model for default namespace field of repo info allows it to be nullable, but the pydantic model doesn't
We allow it to be nullable and also set a default namespace if `should_set_as_default` flag is true
> fix(autofix): Default namespace is supposed to be nullable

- src/seer/automation/autofix/tasks.py
bump it up to make space for codebase indexing until onboarding calls it separately
> fix(autofix): Bump root cause timeout to 1 hr

- src/seer/app.py
- src/seer/automation/autofix/config.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/tasks.py
Because we moved to a step-based stateful architecture where a subsequent steps can be run at any time after another step we need to change how our timeout logic works.
We remove the timeout values in the `AutofixRequest` and introduce new fields for the autofix state:
- `run_timeout_secs` Timeout sections for a current "run" set by the run
- `last_triggered_at` Timestamp for the last time a run was triggered
- `updated_at` Timestamp for the last time the state was updated, this is set by the `ContinuationState` automatically every time the state is set
Fixes a bug where the execution step won't run after the original 30 min timeout
> fix(autofix): Change timeout logic to work with new stateful arch

- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/pipelines.py
- src/seer/automation/pipeline.py
Errors in the new pipelines weren't correctly showing up on the UI after the state change. This makes sure they're caught and presented in the UI accordingly by having an exception handler in each pipeline
Tested e2e locally
> fix(autofix): Log errors in autofix pipelines to ui

- Dockerfile
This updates pip to the latest version, in order to get rid of the warning which shows up every time it's used.
> chore(dev): Update pip

- pyproject.toml
This brings us up to 3.11, which is what we're using elsewhere in the repo.
> chore(dev): Fix Python version in black config in `pyproject.toml`

- .pre-commit-config.yaml
I think our pre-commit config was probably copied from the `sentry` repo, but that means we have a few things there which don't apply to this repo. 
Changes:
- Fix main branch name, from `master` to `main`.
- Remove exclusion of a directory (`fixtures`)  and a file type (SVG) that this repo doesn't have.
> fix(dev): Fix main branch name and excludes in pre-commit config

- Makefile
- README.md
This switches all of our `docker-compose` calls to `docker compose` calls, as per [the V1 -> V2 migration guide](https://docs.docker.com/compose/migrate/) in the docker docs. 
I'm doing this not just because it's nice to be up to date with stuff, but also because GH actions will eventually stop recognizing the old syntax. (They briefly turned it off [two weeks ago](https://github.com/actions/runner-images/issues/9557), everyone freaked out, and they [pushed the date back to July](https://github.com/actions/runner-images/issues/9557#issuecomment-2052607340). Still it's coming.)
> ref(dev): Migrate to new `docker compose` syntax

- src/seer/automation/agent/agent.py
- src/seer/automation/agent/utils.py
- src/seer/automation/codebase/parser.py
- src/seer/db.py
- tests/test_tasks.py
Episode 4 of Man, This Linter Has A Lot Of Opinions: Two changes which _aren't_ behavior changes, but which take at least a little thinking to review before mashing approve, and which are therefore separated into their own PR. 
Changes:
- Use a more efficient regex in `replace_newlines_not_in_quotes` helper. A fuller explanation can be found [here](https://rules.sonarsource.com/python/RSPEC-5857/), but TL;DR `.*?` can require backtracking, whereas just excluding particular characters makes it so the regex engine only has to consider each character in that part of the pattern once. 
- Stop using mutable values as defaults for function parameters, because they are bound when the function is defined, not when it's called, and therefore every call of the function which uses the default uses …
> fix(linting): Vaguely substantive linter fixes

- setup.cfg
This adds config for `flake8`, specifically a handful of rule ignores. With this and all of my recent linter fixes, we can _almost_ turn `flake8` back on in our pre-commit hook.
> feat(linting): Add flake8 config

- notebooks/run_eval.ipynb
- src/migrations/versions/5398765db926_migration.py
- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/models.py
- src/seer/automation/codebase/namespace.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/models.py
- src/seer/db.py
- tests/automation/autofix/test_models.py
- tests/automation/codebase/test_namespace.py
- tests/automation/codebase/test_repo_client.py
Use `external_id` which should be a unique id from the github integration from sentry to reference repos instead of the slug.
Tested locally by sending seer's repo id with `timeseries-analysis-service` old name.
The migration will completely drop the repositories and namespaces tables and create a new one enforcing a non-null `external_id` field which will be sent from sentry. This was a manually made migration...would appreciate a double check.
Depends on https://github.com/getsentry/sentry/pull/69449
> fix(autofix): Link to gh repos with repo id instead of slug

- src/seer/app.py
- src/seer/grouping/grouping.py
we'd like to isolate the embeddings for testing different hardware/deployment configs. creates an endpoint that only calculates embeddings, and no comparisons.
> perf: add endpoint that only calculates embedding

- requirements.txt
Point towards a specific sha to prevent unexpected changes + for some reason when I was running `make update` locally it doesn't use the latest sha???
> fix(deps): Point towards specific sha for sentry sdk

- src/seer/automation/autofix/components/snippet_replacement.py
- src/seer/automation/autofix/utils.py
- tests/automation/autofix/components/test_snippet_replacement.py
- tests/automation/autofix/test_autofix_tools.py
Revert to using xml in the snippet replacement component + trim any newlines
> fix(autofix): Fix newline + quote problems in execution

- src/seer/bootup.py
depending on how we want to tune our deployments for latency vs throughput, configuring the number of threads for pytorch to use is an important lever. this PR lets us do that through an environment variable
see https://huggingface.co/blog/bert-cpu-scaling-part-1#6-core-count-scaling---does-using-more-cores-actually-improve-performance for more info
> perf: add torch num threads env var

- bin/create-and-upload-bench-container.sh
docker commands for buildling uploading local changes to the artifact registry. note the `--no-cache=true --platform=linux/amd64`. building with an M1 means your image won't work on GCP VMs unless you add those flags
> bench: command for building VM

- bin/create-benchmark-request-maker.sh
- bin/create-benchmark-seer-vm.sh
- bin/rm-benchmark-seer-vm.sh
- bin/run-locust-command.sh
these commands are used to create vms for benchmarking seer. they are more of a references as it requires them to be edited for any customizations you'd want to do for them. but a good start!
> perf: add benchmark vm commands

- src/seer/app.py
- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/models.py
- src/seer/automation/codebase/namespace.py
- src/seer/automation/codebase/storage_adapters.py
- src/seer/automation/codebase/tasks.py
- tests/automation/codebase/test_codebase_index.py
Splits out the codebase index creation into a separate creation of the db entries and the index/embedding step. This was needed to be done to return the indexing status to Sentry immediately. In the previous version, it would've needed to wait for a celery worker to pick up the job before the indexing status is present.
This actually plays nicely into splitting up logic that doesn't need the GPU power out (creating the db entries) from the work that does, which is sent to the celery worker.
> ref(codebase): Split codebase create and indexing

- gocd/templates/bash/run-migrations.sh
Adding env-var function explicitly in the script rather than relying on k8stunnel. This should fix the issue we are having with the env vars not being present.
> fix(gocd): Fixing run-migrations script

- src/seer/automation/codebase/namespace.py
- src/seer/automation/codebase/storage_adapters.py
- tests/automation/codebase/test_codebase_index.py
- tests/automation/codebase/test_namespace.py
- tests/automation/codebase/test_storage_adapters.py
Logical failure, because the workspace was using the namespace id for the directory name, we couldn't concurrently run on the same namespace.
Fix: Use a temp dir instead that's cleaned with the storage adapter.
> fix(autofix-codebase): Use tmp dir for workspace

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/pipelines.py
- src/seer/automation/codebase/namespace.py
- src/seer/automation/codebase/storage_adapters.py
- tests/automation/autofix/test_pipelines.py
- tests/automation/codebase/test_codebase_index.py
- tests/automation/codebase/test_namespace.py
- tests/automation/codebase/test_storage_adapters.py
Although we ideally should never create corrupt codebase indexes in the first place, in the words of our very own @corps, _good systems anticipate failures to happen_, and unlike @trillville's "can we just nuke gcs" this will check for corrupt codebase namespaces, delete them, and recreate them on root cause runs.
Each pipeline now also checks for non-corrupt and ready codebase indexes before proceeding.
> feat(autofix): Check & recreate corrupt/broken codebase indexes

- celeryworker.sh
- src/celery_app/app.py
- src/celery_app/config.py
- src/seer/app.py
- src/seer/automation/autofix/pipelines.py
- src/seer/automation/utils.py
- src/seer/bootup.py
- supervisord.conf
Separates our celery setup into a cuda and a cpu queue. With 4 processes (1 per gpu) on the cuda worker and 32 processes on the cpu worker.
Initial codebase indexing & Autofix execution will run on the cuda worker.
Next steps is to split out the work even more + move the potential codebase indexing that happens during a re-index to the gpu
> feat(celery): Separate gpu/cpu celery queue and workers

- supervisord.conf
these logs cause issues on containers with no permissions -- log to stdout instead of creating a file in the container.
> dev: update supervisord container process to log to stdout

- src/seer/automation/codebase/codebase_index.py
- src/seer/automation/codebase/namespace.py
- tests/automation/codebase/test_namespace.py
Couldn't set up autofix on the sentry javascript project because the default namespace id was set to a no-longer-existing codebase
- Make sure the default namespace id is cleared on a delete
- Make sure it's being overwritten on a new create
- The ready check should check the status too
- Skip indexing if the workspace is already ready
- We should add a file check to check whether the files in our index matches the ones in the git repo at the specified sha...
> fix(codebase): Fix default namespace not cleared and not set

- src/seer/automation/pipeline.py
Fixes [SEER-55](https://sentry.sentry.io/issues/5332811854/)
Loading from GCS takes longer, p75 of 7 seconds which would easily make it hit the 15 second soft limit. Increase it to 50 seconds because this should be killing overrun steps not just steps that take long.
> fix(autofix): Increase pipeline step time limits

- src/seer/automation/autofix/steps/create_missing_indexes_chain.py
Fixes [SEER-56](https://sentry.sentry.io/issues/5332812124/)
> fix(autofix): model dump when calling apply_async

- src/seer/automation/autofix/steps/create_index_step.py
- src/seer/automation/autofix/steps/create_missing_indexes_chain.py
- src/seer/automation/autofix/steps/execution_step.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/autofix/steps/steps.py
- src/seer/automation/autofix/steps/update_index_step.py
- src/seer/automation/pipeline.py
- src/seer/automation/steps.py
- tests/automation/autofix/steps/test_autofix_steps.py
Log more tags/metadata to langsmith to aid in debugging and analytics. We will be able to filter by these fields on langsmith ui or by calling their API.
Should also follow up with @colin-sentry on logging these to sentry ai monitoring too
> feat(autofix): Better metadata/tags logging to langsmith

- src/seer/automation/pipeline.py
It confuses pydantic when you pass in the actual celery signatures...they're aren't typed and I can't find how to correctly type them otherwise.
> fix(steps): Change SerializedSignature back to Any

- src/seer/app.py
- src/seer/grouping/grouping.py
- tests/seer/grouping/test_grouping.py
> add delete endpoint to clear grouping records for project

- src/seer/automation/codebase/storage_adapters.py
- tests/automation/codebase/test_storage_adapters.py
Local runs were getting mixed up filesystem storage dumps, we already are deleting before saving to gcs in prod but good to add a test for it too.
> fix(autofix-fs): Make sure storage location is clear

- src/seer/automation/autofix/autofix_context.py
Embedding model's loading condition should be based off of `no_codebase_indexes` which includes the request param not the `skip_loading_codebase` argument, which is only passed on the PR creation.
> fix(autofix): Fix embedding model loading condition

- src/seer/automation/autofix/components/change_describer.py
Noticed the change describer often failed in eval runs I've done, we were expecting a title and description and never provided a format.
When we have time to spare, should consider refactoring this and all our other prompts to use XML to align. also maybe an xml prompt (automatic xml extraction using the pydantic model) extraction util would be useful so we don't have to rely on custom extraction methods for every time we call an llm
> fix(autofix): More reliable Change describer output

- src/seer/automation/codebase/repo_client.py
- src/seer/configuration.py
Fix the annoying github key logs from showing up in dev, also refactor to use the `AppConfig` from dependency injection
> ref(autofix): Stop logging github key issues in dev + use AppConfig

- src/seer/dependency_injection.py
- tests/conftest.py
- tests/test_dependency_injection.py
Fixes two problems:
1.  Running individual pytest cases would fail with an injector issue.  Resolve by insuring `conftest` fully imports the app module and installs it.
2.  Fixes using injection with BaseModel (pydantic).  Test case adjusted.
> Support BaseModel better with @provider and @inject

- .envrc
- Dockerfile
- README.md
- devenv/config.ini
- devenv/sync.py
- requirements.txt
this installs and starts colima (in a way that mounts ~ read-write so that docker compose volume mounts work) in sync.py
this requires devenv >= 1.8.0 so you'll need to download and rerun https://github.com/getsentry/devenv/blob/main/install-devenv.sh
> devenv: install and start colima

- supervisord.conf
this is no longer needed as its not used.
> chore: remove seer-cuda process

- src/seer/app.py
- src/seer/grouping/grouping.py
- tests/seer/grouping/test_grouping.py
- tests/test_seer.py
quickly tested and it takes ~1ms for 100 records on my laptop, we can probably bump this up but lets confirm performance in prod first. i also added some sentry metrics dogfooding stuff - lmk if this seems appropriate
logic:
- take first 100 records from pg, sorted by HNSW index implied distance - no longer include "distance" calculation from pg, require at least 0.05 distance for candidates
- manually calculate cosine distance for all 100 candidates
- rerank based on distance and then return top k
> feat(grouping): add reranking logic

- src/seer/bootup.py
- src/seer/langfuse.py
- tests/test_langfuse.py
looks like we have to call `langfuse_context.configure` before any of the decorators are used, otherwise it messes up the langfuse singleton...we can't do that and use the AppConfig, so we revert to just using the env variables for langfuse but keep the checks in AppConfig
> fix: Fix langfuse init

- src/seer/automation/agent/client.py
- tests/automation/agent/test_client.py
Input and output token counts were swapped by mistake.
> fix(autofix): Fix bug in claude client token counting

- src/seer/automation/autofix/components/root_cause/component.py
Faster and cheaper for a simple step. #999
> (autofix): Switch root cause formatter to gpt-4o-mini

- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- tests/automation/autofix/test_models.py
When a root cause selection is received, we now delete any steps after the root cause step and clear any file changes made so we can re-run cleanly with the new root cause.
> feat(autofix): Enable root cause re-selection

- .github/workflows/test-branches.yml
Could fix why it's failing in main?
Aligns it with [.github/workflows/test-prs.yml](https://github.com/getsentry/timeseries-analysis-service/blob/9d107a916b98f0ea86d4d2d11dd5137326d0fc4b/.github/workflows/test-prs.yml)
> fix: pass EXTRA_COMPOSE_TEST_OPTIONS for env

- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/components/root_cause/prompts.py
An example below of how it's more informative to the user now.
Also results in a small eval bump from 0.43/0.53 to 0.44/0.54 (error weighted/normal).
> (autofix): Prompt engineering to make root cause output descriptions more detailed

- src/celery_app/app.py
- src/celery_app/config.py
- src/seer/automation/autofix/tasks.py
Need to set default queues for celery, for some reason the `default_task_queue` setting doesn't work
> fix(autofix-celery): Set default queues

- src/seer/automation/autofix/components/root_cause/models.py
Should fix https://sentry.sentry.io/issues/5244174915/?project=6178942&query=is:unresolved+issue.priority:%5Bhigh,+medium%5D&statsPeriod=14d&stream_index=0
> fix(autofix): Make repo name have default value to prevent validation error

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/runs.py
- src/seer/automation/autofix/steps/change_describer_step.py
- src/seer/automation/autofix/steps/coding_step.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/autofix/tasks.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/autofix/test_autofix_event_manager.py
- tests/automation/autofix/test_autofix_tasks.py
- tests/automation/autofix/test_models.py
- tests/automation/autofix/test_runs.py
Allows multiple of the same step inside an autofix run.
Each step in the autofix step state will now have a unique UUID, with the unique strings now in the `key` field.
Backwards compatible and will migrate existing runs via `event_manager.migrate_step_keys()`
> feat(autofix): Allow repeating steps + backwards compatibility

- src/seer/automation/autofix/components/coding/utils.py
- src/seer/automation/autofix/steps/change_describer_step.py
- src/seer/automation/autofix/steps/coding_step.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/autofix/steps/steps.py
- src/seer/automation/autofix/utils.py
- src/seer/automation/utils.py
- tests/automation/autofix/steps/test_autofix_steps.py
- tests/automation/autofix/test_autofix_utils.py
Allow steps to retry on an exception, this is like a high-level catch all for issues that we don't specifically handle.
Current retry settings:
1. Root cause -> maximum 2 retires or 3 runs max
2. Plan+Code-> maximum 2 retries or 3 runs max
3. Change Describer -> maximum 1 retries or 2 runs max
> feat(autofix): Allow steps to retry on an exception

- requirements.txt
Langfuse python SDK added support for openai structured output in [v2.43.1](https://github.com/langfuse/langfuse-python/releases/tag/v2.43.1), this bumps the commit in my fork to include those changes. 
Currently is broken:
> chore: Bump langfuse sdk to 2.43.3 + forked commits

- src/seer/automation/models.py
Issue #1058 
The reason some issues got "Error loading issue summary" was because they had None for an error message, which our Pydantic model didn't accept.
> (issue summary) Make ExceptionDetails value optional to handle issues without error message

- src/seer/automation/models.py
- tests/automation/autofix/test_models.py
For both Autofix and Issue Summary, limit the number of stacktrace frames we use to 16.
Prioritizes cutting out frames that aren't in-app.
Issue #1056
> (autofix/issue summary) Trim stacktrace frames

- src/seer/configuration.py
- src/seer/json_api.py
- tests/test_json_api.py
In production, ensure that api signatures are provided, and reject requests that lack it.
> Require api signatures for json_api

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/coding/models.py
- src/seer/automation/autofix/components/coding/prompts.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/root_cause/prompts.py
- src/seer/automation/autofix/prompts.py
- src/seer/automation/models.py
1. We weren't passing the original human instructions into the plan+code agent. This fixes that
2. Also, both root cause and plan+code agents will have the list of repos provided to it, to reduce the chance it gets confused over repos
3. Also removes the no-longer-used repo_id field.
> fix(autofix): Fix repo confusion + lack of instructions in plan+code

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/models.py
- src/seer/automation/summarize/issue.py
- src/seer/automation/summarize/models.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/autofix/test_models.py
- tests/automation/summarize/test_issue.py
Included in this PR:
1. Optionally takes in trace connected issues for an issue to inform the summary output. (#1071 )
2. Attempts to trim `vars` in a stacktrace frame if they get lengthy.
3. Fixes `ValidationError` for exceptions without a stacktrace by making the stacktrace optional. (#1084 )
> feat(issue summary): Add support for trace connected issues

- src/seer/automation/autofix/components/coding/utils.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/models.py
We weren't using the commit message output from the plan+code agent
> fix(autofix): Use commit message from plan+code

- src/seer/automation/models.py
Some issues don't have all the breadcrumbs fields, so we make them optional now.
> fix(issue summary) Make breadcrumb fields optional to prevent validation errors

- .github/workflows/tests.yml
- docker-compose.yml
- requirements.txt
- src/seer/configuration.py
- src/seer/json_api.py
- tests/test_json_api.py
Mainly for the staging deployment in `ml-ai`
Introduces an `ENFORCE_API_AUTH` env variable that will enforce either the rpc secret signing or the bearer token.
> feat(security): Add API bearer token auth via JWT

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/coding/models.py
- src/seer/automation/autofix/components/coding/prompts.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/components/root_cause/prompts.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/prompts.py
- src/seer/automation/autofix/steps/coding_step.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/summarize/issue.py
- tests/automation/autofix/components/test_root_cause.py
- tests/automation/autofix/steps/test_root_cause_step.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/summarize/test_issue.py
This PR includes:
1. Changing the issue summary storage logic to store the raw output `IssueSummary` from GPT, rather than the trimmed `SummarizeIssueResponse` as before. The extra info, such as `reason_step_by_step` is useful.
2. Pass the issue summary to Autofix as additional context. (part of #998) Remove pre-processing step on event details as well. Improvement in evals: 0.48/0.52 -> 0.51/0.55
3. Allow optional issue summary in `AutofixRequest` to support new eval dataset
> (autofix): Pass issue summary to autofix, store raw summary output instead of response

- src/seer/automation/autofix/components/coding/component.py
Switches coding agent to Claude (#951)
Evals: 0.51/0.55 -> 0.54/0.61 (huge bump!)
Note: don't deploy this until Sept 5, 2024
> feat(autofix): Switch coding agent to claude

- src/seer/automation/autofix/tools.py
- tests/automation/autofix/test_autofix_tools.py
Adds a file search and a file search wildcard tool to autofix (and soon the other codegen agents)
> feat(autofix/codegen): File search tools

- docker-compose.yml
- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/bootup.py
Use mode preloading mechanism to force numba compilation for Stumpy library
> (dynamic alert thresholds) Force recompilation of Stumpy library during bootup

- src/seer/anomaly_detection/detectors/mp_utils.py
- Util raises exception if requested length for padding is less than current mp_dist array
Note: is there a more graceful way to handle this?
> fix(anomaly-detection): Handle illegal padding amount

- src/seer/json_api.py
- tests/test_json_api.py
By using URL as part of the payload that is signed we are assuming that URL used by client will be same as the URL seen in the request payload on Seer end. This is not true as requests from Subscription processor has full UTL including server name while those from the UI do not.
This PR makes URL optional. This will be step 1 of the fix. We need to follow this up with two more changes:
* remove URL from all locations on the client end where we are signing Seer requests
* once we confirm that Seer is not getting requests with URL anymore, then remove the code that checks for URL + payload.
> chore(auth): Exclude URL from auth check as it can differ between environments

- src/seer/automation/agent/client.py
- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/coding/models.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/components/root_cause/prompts.py
- src/seer/automation/autofix/evaluations.py
- tests/automation/autofix/components/coding/test_coding_models.py
- tests/automation/autofix/components/test_root_cause.py
- tests/automation/autofix/test_autofix_evaluations.py
- tests/automation/autofix/test_models.py
1. Introduces reproduction step in root cause output.
2. Uses gpt4o w/ structured output for the root cause for increased reliability
3. (Tacking on) Adds claude agent back into the plan+code agent
(Before is above, after is below)
> feat(autofix): Reproduction in root causes

- src/seer/configuration.py
I'll share 1password links to add this to your local environments, and I'll get this in staging
In production we'll have IAP which I'm working on.
> Making codecov super token available for the moment

- src/seer/grouping/grouping.py
- tests/seer/grouping/test_grouping.py
Add `on_conflict_do_nothing` for inserting group records
fixes [SEER-9Y](https://sentry.sentry.io/issues/5754951463/)
> chore(similarity): Add try catch around insert grouping record

- codecov.yml
- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/anomaly_detection_di.py
- src/seer/anomaly_detection/detectors/__init__.py
- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- src/seer/anomaly_detection/detectors/mp_scorers.py
- src/seer/anomaly_detection/detectors/normalizers.py
- src/seer/anomaly_detection/detectors/window_size_selectors.py
- src/seer/tags.py
- tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py
- tests/seer/anomaly_detection/detectors/test_mp_scorers.py
- tests/seer/anomaly_detection/detectors/test_nomalizers.py
- tests/seer/anomaly_detection/detectors/test_window_size_selectors.py
- tests/seer/anomaly_detection/test_anomaly_detection.py
This PR fixes two issues with anomaly detection logic with regards to time series with zero variance:
* SuSS logic for window size selection fails
* the interquartile range based scoring logic results in false positives
These two issues are fixed by
* defaulting the window size to 3 if SuSS logic fails
* using mean of a context window instead of IRQ for time series with low variance
It also includes additional changes to increase test coverage of anomaly detection code and additional tags to track frequency of low variance time series.
> chore(anomaly_detection) Handle timeseries with very low variance

- src/seer/grouping/grouping.py
- tests/seer/grouping/test_grouping.py
- tests/test_seer.py
Handle optional message in grouping records
> ref(similarity): Handle optional message

- docker-compose.yml
- src/celery_app/app.py
- src/celery_app/tasks.py
- src/seer/configuration.py
- tests/test_celery.py
1.  Abstract the notion of deployment questions into the `AppConfig` object with new properties.  NOTE:  Deployments are not considered discrete, they can overlap, as per local development.
2.  Check for deployment type either by explicit environment variable or by the hostname (confirmed the deployment name in our k8s config reflects in production host names).
3.  Conditionalize beat tasks by deployments.
4.  Tests.  Add your new beat job to the anomaly detect test to validate it becomes a condiational beat task.
> Adds per deployment beat configuration

- src/seer/automation/autofix/components/coding/models.py
- src/seer/automation/autofix/components/coding/prompts.py
Two quick but impactful fixes for plan+code
1. Some root causes don't have a code snippet now, that was causing a lot of the errors
2. It often likes to create files that already exist, this is a preliminary prompting fix, will have more robust follow up fix
Reduces error rate in plan+code, but not all just yet
Before:
After:
> fix(autofix): PlanCode snippet and new file quick fixes

- gocd/templates/bash/deploy.sh
right now i don't think our deploy script is updating the seer-gpu service. this should fix it.
> fix: update seer gocd script to update seer-gpu

- src/seer/automation/agent/agent.py
- src/seer/automation/autofix/components/insight_sharing/component.py
- tests/automation/agent/test_agent.py
- tests/automation/autofix/components/test_insight_sharing.py
Before, insight cards would be generated on every iteration synchronously, slowing down the whole experience. Now, they're generated in a separate thread, so it's a lot faster.
Also, a smattering of prompt engineering is included in this PR.
> (autofix): Generate insight cards on separate thread async

- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/coding/models.py
- src/seer/automation/autofix/components/coding/prompts.py
- src/seer/automation/autofix/components/coding/utils.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/utils.py
- src/seer/langfuse.py
- tests/automation/autofix/components/coding/test_coding_component.py
- tests/automation/autofix/components/coding/test_coding_utils.py
Makes plan+code agent much more reliable with
1. Handle incorrect file operations (edit file that doesn't exist, create file that already exists, etc)
2. Fix incorrect diffs
We now have a 0% plan/code error rate and much lower missing change rate
Before:
After:
> feat(autofix): Plan+Code file handling and diff fixer

- src/seer/automation/agent/client.py
- src/seer/automation/autofix/components/coding/prompts.py
- src/seer/automation/codegen/unit_test_coding_component.py
The response from Claude was being truncated due to the smaller token size. 
This PR also fixes an issue where the incorrect type was being passed into `CodeUnitTestOutput`. It should only take in a list of `FileChange` types.
> [fix] Increase Anthropic max output size and fix test generation output

- src/seer/automation/autofix/components/coding/models.py
- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/components/root_cause/prompts.py
- src/seer/automation/autofix/utils.py
- tests/automation/autofix/components/test_root_cause.py
Adds a simple unit test that reproduces (intentionally failing) to the root cause output. The goal for this is to easily be copied.
> feat(autofix): Add unit test to root cause output

- src/seer/automation/codebase/repo_client.py
- src/seer/automation/codegen/unit_test_github_pr_creator.py
- src/seer/automation/codegen/unittest_step.py
- tests/automation/codegen/test_unit_test_step.py
This change creates a new PR with the `base` set to the PR where unit tests are generated.
The user can kick off this flow by hitting the `/v1/automation/codegen/unit-tests` endpoint. 
Example PR created using this flow: https://github.com/rohitvinnakota-codecov/hello-world-sunday/pull/2
> [feat] Auto create a PR after the unit test task completes

- src/seer/app.py
- src/seer/automation/agent/agent.py
- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/insight_sharing/component.py
- src/seer/automation/autofix/components/insight_sharing/models.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/steps/change_describer_step.py
- src/seer/automation/autofix/steps/coding_step.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/autofix/steps/steps.py
- src/seer/automation/autofix/tasks.py
- src/seer/automation/pipeline.py
- src/seer/automation/utils.py
- tests/automation/agent/test_agent.py
- tests/automation/autofix/components/test_insight_sharing.py
- tests/automation/autofix/components/test_root_cause.py
- tests/automation/autofix/steps/test_autofix_steps.py
- tests/automation/autofix/test_autofix_event_manager.py
- tests/automation/autofix/test_autofix_tasks.py
- tests/automation/autofix/test_models.py
- tests/test_seer.py
When an certain update request is received, we jump back to the selected point in the steps/insights chain, delete any steps, insights, and memory after that, add the user feedback to the memory, and continue analyzing.
This allows the user full control over the model's reasoning, and let's them rethink and guide the model at any point. This also allows restarting from errored/no-root cause states, and jumping back to previous steps.
> feat(autofix): Add controllable insights chain

- gunicorn.sh
from talking with @corps, this script causes bootup logs to be prefixed with `src.`, which causes them to not be logged because our logging filter excludes them. https://github.com/getsentry/seer/blob/7d9af0b8dd3e95a740b07407c11687e05e3836f6/src/seer/bootup.py#L40
> ref(init): change seer bootup script

- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/tools.py
- src/seer/automation/codegen/unit_test_coding_component.py
- src/seer/langfuse.py
- tests/automation/autofix/test_autofix_tools.py
The keyword search tool will only download the repo into a temp directory once. You will now need to use basetools with the context manager:
```
with BaseTools(self.context) as tools:
```
the tmp dir and downloaded repo will be deleted at the closing of the context manager.
> feat(autofix): Keyword search only downloads repo once

- src/seer/automation/agent/client.py
- src/seer/automation/autofix/evaluations.py
- src/seer/automation/autofix/tasks.py
Bumps gpt-4o in the root cause agent to the latest version (08-06). Bumps scoring model to o1-mini.
Evals (ignore second row) show that new model is at least as good as the old one, if not slightly better:
Anecdotally, the eval also ran ~5-6 minutes faster, and I didn't even bump the scoring model at this point (for consistency's sake). 
After bumping the scoring model too, the new baseline is:
> (autofix): Bump 4o version to latest

- src/seer/app.py
Add an endpoint that raises an Exception intentionally. This is so we can test creating a suspect commit comment in prod and test the GitHub Copilot extension.
This should definitely be removed after testing/demoing is done.
> (autofix): Add bad endpoint

- src/celery_app/tasks.py
- src/seer/app.py
- src/seer/automation/tasks.py
- tests/test_celery.py
Removes the error-raising endpoint and adds a celery job to do the same thing.
This is all for testing GH Copilot in prod, should be removed later.
> (autofix): Add celery job that throws an error every minute

- src/seer/automation/codegen/unit_test_github_pr_creator.py
- tests/automation/codegen/test_unit_test_step.py
Create a branch that merges against the original PR branch instead of the repo's default branch. 
Example of testing locally: https://github.com/rohitvinnakota-codecov/hello-world-sunday/pull/13
> [fix] Update branch ref for unit test generation 

- requirements-constraints.txt
- requirements.txt
- src/seer/automation/agent/agent.py
- src/seer/automation/agent/client.py
- src/seer/automation/agent/models.py
- src/seer/automation/agent/tools.py
- src/seer/automation/autofix/autofix_agent.py
- src/seer/automation/autofix/components/change_describer.py
- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/insight_sharing/component.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/evaluations.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/codegen/unit_test_coding_component.py
- src/seer/automation/summarize/issue.py
- src/seer/automation/summarize/replays.py
- tests/automation/agent/test_agent.py
- tests/automation/agent/test_client.py
- tests/automation/autofix/components/coding/test_coding_component.py
- tests/automation/autofix/components/test_insight_sharing.py
- tests/automation/autofix/components/test_root_cause.py
- tests/automation/autofix/test_autofix_agent.py
- tests/automation/autofix/test_autofix_evaluations.py
- tests/automation/summarize/test_issue.py
- tests/automation/summarize/test_replays.py
- tests/generators.py
We were calling LLMs in multiple different ways, and the llm clients and the agents were getting somewhat unwieldy, so this refactoring work aims to simplify, unify, and optimize how we interact with LLMs.
The LLM clients now follow a similar interface to the [vercel ai sdk](https://sdk.vercel.ai/docs/ai-sdk-core/overview), the two main methods you will interact with is `generate_text` and `generate_structured`, where the former is for normal completion and the latter is for structured output completion. The structured output completion currently only works with the OpenAI provider for now.
The LLM providers, `OpenAiProvider` and `AnthropicProvider` contains all the specific logic for each provider, you select the model via the provider and pass it to the generate calls, for example …
> ref(autofix): New llm client and agent interface

- src/seer/automation/autofix/components/insight_sharing/models.py
- src/seer/automation/models.py
Fixes:
1. https://sentry.sentry.io/issues/5734622145/?project=6178942&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=7d&stream_index=14
2. https://sentry.sentry.io/issues/5483941395/?node=txn-4644023d16bd4b95a13ee0d9df5e6dfc&project=6178942&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=7d&stream_index=9
3. https://sentry.sentry.io/issues/5950117420/?node=txn-2f268cd4745e4e6baab73d6c8e905770&project=6178942&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=7d&stream_index=7
> fix(autofix+issue summary): Fix various validation errors

- src/celery_app/tasks.py
- src/seer/automation/tasks.py
- tests/test_celery.py
> chore(copilot): add new bug

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/tools.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/codegen/codegen_context.py
- src/seer/automation/codegen/unit_test_coding_component.py
- src/seer/automation/codegen/unittest_step.py
- src/seer/configuration.py
For unit test gen, use the codecov github app for repo client if available, if not fallback to autofix app
Tested with both unit test gen and autofix to make sure this doesn't break anything.
> feat(unit-test): Use codecov unit test gh app and fallback to autofix app if not present

- src/seer/automation/agent/client.py
- tests/automation/agent/test_client.py
The prompt should be appended to the end, not the start of the messages. This also adds tests to validate that the messages and tools are prepped correctly.
> fix(autofix): Fix llm client message order

- src/seer/automation/codebase/repo_client.py
- src/seer/automation/codegen/unit_test_github_pr_creator.py
- tests/automation/codebase/test_repo_client.py
Posts a comment to the original PR once unit test generation is complete.
> [feat] Post comment to PR post unit test generation

- src/seer/automation/models.py
Fixes a ValidationError when an event payload doesn't have this field. [Sentry Issue](https://sentry.sentry.io/issues/6013887390/?node=txn-e68fd8207bc24ef7ba9a8a0eb963d44e&project=6178942&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=7d&stream_index=2)
> fix(autofix + issue summary): Make handled field optional

- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/components/root_cause/prompts.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/steps/root_cause_step.py
- tests/automation/autofix/components/test_root_cause.py
- tests/automation/autofix/steps/test_root_cause_step.py
Generates a short explanation for why Autofix failed to find a root cause. Also sends it the frontend so we can show it like this:
> feat(autofix): Add explanation when no root cause found

- src/seer/automation/autofix/prompts.py
- src/seer/automation/summarize/issue.py
- tests/automation/autofix/steps/test_root_cause_step.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/summarize/test_issue.py
Remove impact section from generation since we're not using it to let the model focus (but still preserve the model we're sending to the frontend).
Prompt engineer the summary to be bulleted shorthand.
> feat(issue summary): Make issue summary bulleted, remove impact

- src/seer/automation/autofix/components/coding/component.py
Bumps to Claude 3.5 v2 for the coding step.
Baseline main eval: 0.61/0.63
New Claude coding: 0.61/0.63
New Claude root cause + coding: 0.59/0.63
So only bumping Claude for the coding step. Not really an improvement in the evals but worth bumping anyway in case.
BEFORE MERGING: enable the new model in the prod GCP project
> chore(autofix): Bump claude version

- src/seer/anomaly_detection/tasks.py
- Add `alert_id` as a tag to the `cleanup_timeseries` transaction on Sentry
> Add alert_id tag to cleanup transaction

- src/seer/db.py
Order the timestamps in `dynamic_alert` table to ensure consistency across queries
> chore(anomaly detection): Order Dynamic Alert Timestamps

- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/coding/prompts.py
- src/seer/automation/autofix/components/is_fix_obvious.py
- src/seer/automation/autofix/components/is_root_cause_obvious.py
- src/seer/automation/autofix/components/root_cause/component.py
- tests/automation/autofix/components/coding/test_coding_component.py
- tests/automation/autofix/components/test_is_fix_obvious.py
- tests/automation/autofix/components/test_is_root_cause_obvious.py
- tests/automation/autofix/components/test_root_cause.py
Pre-expands code files from the Root Cause Step's relevant code context. Then asks an LLM if we can make the fix without any further searching to decide if we give the agent tools or not.
- cost down to 30 cents per run
- shaves 30 seconds off run time
- maintains eval scores
> feat(autofix): Add short circuit to plan and code step

- src/seer/automation/autofix/components/is_fix_obvious.py
- src/seer/automation/autofix/components/is_root_cause_obvious.py
- tests/automation/autofix/components/test_is_root_cause_obvious.py
We were just dumping the raw `event_details` object in there, when we should've been calling `format_event()`.
> fix(autofix): Fix formatting for short circuit prompts

- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/insight_sharing/component.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/tasks.py
- tests/automation/autofix/test_autofix_tasks.py
The memory truncation logic upon a rethink always kept only 1 memory item if you did it from before the first insight card. This broke certain cases in the plan+code step since it can have multiple initial messages. #1371 
This PR fixes that by tracking how many items make up the "initial prompt". 
(also tacking on a small prompt tweak for insight sharing that seems to help with #1372
> fix(autofix): Fix rethink bug in plan+code due to pre-expanded files

- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- src/seer/anomaly_detection/detectors/location_detectors.py
- src/seer/anomaly_detection/detectors/mp_scorers.py
- src/seer/anomaly_detection/tasks.py
- tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py
- tests/seer/anomaly_detection/detectors/test_location_detectors.py
- tests/seer/anomaly_detection/detectors/test_mp_scorers.py
- tests/seer/anomaly_detection/test_anomaly_detection.py
- tests/seer/anomaly_detection/test_cleanup_tasks.py
This change ensures that the direction logic is applied for anomalous points even when the alert is configured for both directions. This change helps reduce noise from anomalies that do not breach any threshold.
Note: Apart the core logic of enabling direction logic, this PR also includes multiple fixes for the time stamps not being handled correctly that surfaced due to this change.
> chore(anomaly_detection): apply direction logic for alerts with both as direction

- src/seer/automation/autofix/components/root_cause/component.py
Model switch from GPT 4o to Claude 3.5 Haiku results in better latency, better coding, and better root cause results.
(see row 2 below):
> chore(autofix): Switch to claude for root cause step

- src/seer/anomaly_detection/accessors.py
- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/anomaly_detection_di.py
- src/seer/anomaly_detection/detectors/__init__.py
- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- src/seer/anomaly_detection/detectors/smoothers.py
- src/seer/anomaly_detection/detectors/window_size_selectors.py
- src/seer/anomaly_detection/models/timeseries.py
- src/seer/anomaly_detection/models/timeseries_anomalies.py
- tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py
- tests/seer/anomaly_detection/detectors/test_smoothers.py
- tests/seer/anomaly_detection/models/test_timeseries_anomalies.py
- tests/seer/anomaly_detection/test_accessors.py
- tests/seer/anomaly_detection/test_anomaly_detection.py
- Fix stream smoothing by keeping track of `original_flag` in the `anomaly_algo_data` for each flag
- Use a voting threshold smoothing for the last set of points and their original flags
> fix(anomaly detection): Fix Stream Smoothing

- src/seer/anomaly_detection/detectors/mp_scorers.py
- tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py
- tests/seer/anomaly_detection/detectors/test_mp_scorers.py
Disabling this as a stopgap approach. We need to dig into the interplay between the flip-flop logic and this before restoring.
> chore(anomaly-detection): disable direction detection for points that are not close to thresholds

- requirements-constraints.txt
- requirements.txt
- src/seer/automation/autofix/utils.py
Reimplement our fuzzy matcher using `rapidfuzz` to greatly improve efficiency.
No impact on evals, except for a 10s latency improvement.
Great performance benchmarks:
> feat(autofix): Optimize fuzzy matcher

- src/seer/automation/models.py
- tests/automation/test_automation_models.py
Autofix was removing trailing newlines when applying files for pr creation.
The added unit test fails without this change, passes with the change.
> fix(autofix): preserve trailing newlines in files when applying patches

- src/seer/automation/autofix/components/coding/component.py
We were storing the wrong agent's memory.
> fix(autofix): Store the correct agent memory in simple fixer

- src/seer/automation/autofix/tools.py
Marks required parms in tool definitions as `required`. This should hopefully force the LLM APIs to provide the required params and not cause errors. Hopefully fixes: https://sentry.sentry.io/issues/5537615520/
> fix(autofix): Mark tool params as required

- src/seer/automation/autofix/components/root_cause/component.py
- tests/automation/autofix/components/test_root_cause.py
Adds parsing to fix this edge case when the agent returns a reason for not finding any root causes. #1480
> fix(autofix): Handle parsing edge case for no root cause termination reason

- src/celery_app/tasks.py
- src/seer/anomaly_detection/tasks.py
- tests/seer/anomaly_detection/test_cleanup_tasks.py
- tests/test_celery.py
- Currently, cleanup only happens upon detection call leaving stale timestamps for disabled alerts to accumulate
- Created cron which runs weekly to cleanup (delete) disabled alerts based on when they were last queued for detection (28 days) or if last_queued is null then deletes old alerts
- Cleaning alerts as a byproduct cleans the timeseries that are associated with them because of the parent-child relationship
> feat(anomaly detection): Cron to cleanup disabled alerts

- src/seer/app.py
- src/seer/automation/codegen/models.py
- src/seer/automation/codegen/tasks.py
Initial work to provision endpoints. 
Full plan is captured here: 
https://github.com/orgs/codecov/projects/31/views/11?pane=issue&itemId=NaN&issue=codecov%7Cengineering-team%7C2678
> [feat] Create endpoints to handle reviewing a PR and checking state of the review

- src/seer/automation/agent/client.py
- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/insight_sharing/component.py
- src/seer/automation/autofix/components/root_cause/component.py
- tests/automation/agent/test_client.py
1. Adds a cleaning util for LLM memory that fixes empty content messages
2. Moves the `clean_tool_call_assistant_messages` inside `generate_structured` and `generate_text` so that we don't have to think about cleaning memory when using the LLMClient
Fixes #1483
> fix(autofix): Handle empty messages and move cleaning calls inside LLMClient

- src/seer/app.py
- src/seer/automation/agent/client.py
- src/seer/automation/summarize/issue.py
- tests/test_seer.py
Set the openai call to timeout at 7s (p99 is 4.0 seconds) and return a 504 in that case, 500 otherwise.
> fix(issue-summary): Better handle errors from openai

- src/seer/anomaly_detection/accessors.py
- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/anomaly_detection_di.py
- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- src/seer/anomaly_detection/detectors/mp_config.py
- src/seer/anomaly_detection/models/__init__.py
- src/seer/anomaly_detection/models/dynamic_alert.py
- src/seer/anomaly_detection/models/timeseries_anomalies.py
- src/seer/anomaly_detection/tasks.py
- src/seer/db.py
- tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py
- tests/seer/anomaly_detection/models/test_timeseries.py
- tests/seer/anomaly_detection/models/test_timeseries_anomalies.py
- tests/seer/anomaly_detection/test_accessors.py
- tests/seer/anomaly_detection/test_anomaly_detection.py
- tests/seer/anomaly_detection/test_cleanup_tasks.py
Please review the [validation notebook](https://github.com/getsentry/ml-models/blob/main/anomaly_detection/validation.ipynb) for examples of the dynamic window in action!
- Use 2 windows (1 determined by the SuSS algorithm, and a "fixed" window at size 10) to perform detection reducing the recovery time for the algorithm ultimately making alerts persist for a shorter period of time after anomalous behavior is over
- Performing detection twice for each window to maintain the matrix profiles
- Updated the `anomaly_algo_data` to store matrix profile related information for both windows for a given alert
- Created `MPTimeSeriesAnomaliesSingleWindow` class and updated the `MPTimeSeriesAnomalies` class to effectively manage and store the proper matrix profile related information and the boolean …
> feat(anomaly detection): Dynamic Window for Matrix Profiling

- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/root_cause/models.py
- tests/automation/autofix/components/test_root_cause.py
Uses our fuzzy matcher to find the matching snippets for the generated relevant code context snippets, then saves the line number range in the output. Issue #1529 
Frontend PR will make them show up, but nothing breaks if this backend PR is merged.
> feat(autofix): Add line numbers to code context snippet

- src/seer/app.py
- src/seer/automation/codebase/models.py
- tests/test_seer.py
Remove copilot testing endpoint and codebase indexing endpoint since they are unused now (correct me if I'm wrong)
> chore(autofix): Remove dead endpoints

- src/seer/automation/autofix/state.py
- src/seer/automation/codegen/state.py
- src/seer/automation/state.py
- tests/automation/autofix/test_autofix_state.py
Runs were timing out because there actually are two `updated_at` fields, the main one being used in the class instances are the ones inside the `value` json. We're supposed to be syncing the field on the db model with the one from the json for the sake of db querying, but there was a bug in the big PR that updates this field in the value AFTER the value json was set.
So the updated_at inside the json was the original one, never bumped.
> fix(autofix): Bump updated_at BEFORE throwing the state in the dbmodel

- src/seer/automation/autofix/event_manager.py
When starting a new step due to rethinking or Q&A, mark the state as triggered to prevent premature timeouts.
> fix(autofix): Mark triggered for interactive starts

- src/seer/automation/codebase/code_search.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/utils.py
- tests/automation/codebase/test_repo_client.py
This PR changes the autofix logic to create a single commit for the suggested fix.
- All the files changes are grouped together using the Github data API.
- The original commit messages might not be meaningful after user-suggested patching, so they are not used
> feat(autofix) create a single commit for the suggested fix

- src/seer/automation/autofix/prompts.py
- src/seer/automation/summarize/issue.py
- tests/automation/autofix/steps/test_root_cause_step.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/summarize/test_issue.py
The LLM could be overindexing on "connected" issues, so we just call it issues from the same application session.
Output stays the same, we just rename it for the LLM
> fix(issue-summary): Rename connected issues in prompt to session related

- src/seer/automation/agent/agent.py
When the question asking tool was used, it would end the agent run but the `agent.run` call returns the tool call with `"."` as the content of the last message, causing the root cause and plan/code components to error
> fix(autofix): Fix user question not ending agent run

- src/seer/anomaly_detection/accessors.py
- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- tests/seer/anomaly_detection/test_accessors.py
- tests/seer/anomaly_detection/test_cleanup_tasks.py
- `thresholds` and `original_flags` for the respective detector (SuSS vs. fixed) were not being properly used and therefore defaulting to just SuSS
- Ensure that use_suss flag is being properly used (entire history was being sent not the required portion)
- Clean up `combine_anomalies` for readability and performance (if no fixed window is being used, should not perform list iteration)
> fix(anomaly detection): Use thresholds for dynamic window

- src/seer/automation/agent/client.py
- src/seer/automation/autofix/autofix_agent.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- tests/automation/agent/cassettes/test_anthropic_generate_text_stream.yaml
- tests/automation/agent/cassettes/test_anthropic_generate_text_stream_with_tools.yaml
- tests/automation/agent/cassettes/test_openai_generate_text_stream.yaml
- tests/automation/agent/cassettes/test_openai_generate_text_stream_with_tools.yaml
- tests/automation/agent/test_client.py
- tests/automation/autofix/cassettes/test_autofix_run_happy_path.yaml
- tests/automation/autofix/cassettes/test_run_iteration_no_help_prompt_when_not_needed.yaml
- tests/automation/autofix/cassettes/test_run_iteration_prompts_for_help_at_interval.yaml
- tests/automation/autofix/cassettes/test_run_iteration_prompts_for_help_near_max_iterations.yaml
- tests/automation/autofix/cassettes/test_run_iteration_with_insight_sharing.yaml
- tests/automation/autofix/cassettes/test_run_iteration_with_queued_user_messages.yaml
- tests/automation/autofix/cassettes/test_share_insights_no_new_insights.yaml
- tests/conftest.py
Replaces Autofix agent LLM calls with streaming. Saves the output as it comes in the step object in the run state. All other functionality is identical.
I added a function for streaming with OpenAI as well, and tested that it works, but we don't use it at the moment. Just future proofing.
> feat(autofix): Stream output in Autofix agent

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/codebase/repo_client.py
- tests/automation/codebase/test_repo_client.py
See [this profile](https://sentry.sentry.io/profiling/profile/seer/ba56c3e354674bf5bc18c9ca696400e9/flamegraph/?colorCoding=by%20system%20vs%20application%20frame&eventId=acec842a014c44818c8bc5a7263abf65&fov=2984499968,38,7125656064,17&query=&sorting=call%20order&tid=138847897326720&view=top%20down).
We were creating new repo clients over and over again, and each time, it added 1-1.5s.
- before invoking a step, ~1.5s redundant
- pre-filling coding step memory: ~5s (more for more files)
- every expand_document tool call: ~1s
This PR stores created repo clients in memory in the context so that throughout a single step, we only need to initialize one repo client for each repo.
> fix(autofix): Cache repo client objects to avoid re-initialization

- src/seer/automation/autofix/autofix_agent.py
- tests/automation/autofix/cassettes/test_autofix_run_happy_path.yaml
- tests/automation/autofix/cassettes/test_run_iteration_with_insight_sharing.yaml
- tests/automation/autofix/test_autofix_agent.py
Issue #1630 
I discovered in profiling that when the root cause step completed, there was sometimes a huge wait (the case I saw was 6 seconds) for the thread pool to finish it's last insight card generation, before moving onto the root cause formatter. (similar for the coding step)
Why? Because we started a new insight sharing thread after every LLM call, including the final call of the agent run. Due to Zach's changes that make us wait for threads to complete before ending the run, this caused big delays.
Solutions in this PR:
1. Don't generate an insight card on the final output of the run. That was somewhat redundant anyway if we're about to show the final output card, plus this avoids starting a new thread from scratch that blocks everything else.
2. Adds a second thread worker. That …
> fix(autofix): Prevent long wait times for insights threadpool at end of run

- README.md
- celeryworker.sh
- src/celery_app/config.py
- src/celery_app/tasks.py
- src/seer/automation/autofix/steps/coding_step.py
- src/seer/automation/autofix/tasks.py
- src/seer/automation/codegen/tasks.py
- src/seer/automation/steps.py
- src/seer/configuration.py
- supervisord.conf
- tests/test_celery.py
Setting `CELERY_WORKER_QUEUE` env var will make that instance of seer both publish tasks to and the celery worker consume from the queue with that name.
Will follow up w/ SRE to set this value.
> feat(celery): Set celery worker queue via CELERY_WORKER_QUEUE

- src/seer/automation/autofix/components/coding/prompts.py
In the case where we switch to a simple fixer after the full fixer is in memory, we already added a special instruction. Just appending a line to that to clarify that the agent can't use any tools. Should help with #1637 but hard to verify. FWIW I could never reproduce it locally.
> fix(autofix): Add line to prompt to clarify to agent that it can't use tools

- src/seer/anomaly_detection/anomaly_detection.py
- Includes the ad_config json in the logs upon storing the alert and when the `insufficient_timeseries_data` error is thrown
> chore(anomaly detection): Include ad_config in store log

- src/seer/automation/autofix/autofix_agent.py
- tests/automation/autofix/cassettes/test_get_completion_interrupts_with_queued_messages.yaml
- tests/automation/autofix/test_autofix_agent.py
Before, the interjection interaction had to wait for LLM calls to complete before it actually interrupted. Now that we have streaming, we can interrupt much quicker and make the interaction more responsive to the user.
> feat(autofix): Makes interjection interaction interrupt LLM stream for more responsiveness

- src/seer/db.py
- Enable the `pool_pre_ping` flag to allow connections to confirm disconnect and recycle all connections older than the current
- Pessimistic handling in this case should be correct since the connection is not dropped in the middle of a transaction
https://docs.sqlalchemy.org/en/20/core/pooling.html#pool-events
> fix(anomaly detection): Recycle connection upon disconnect

- src/seer/anomaly_detection/accessors.py
- Use `session.flush()` after the executed statement to separate delete and insert queries
Sources:
- https://m1lt0n.github.io/sqlalchemy/orm/python/delete-before-insert-sqlalchemy/
- https://github.com/sqlalchemy/sqlalchemy/issues/2501
- https://stackoverflow.com/questions/4201455/sqlalchemy-whats-the-difference-between-flush-and-commit
- https://docs.sqlalchemy.org/en/20/orm/session_basics.html#flushing
> fix(anomaly detection): Fix Integrity Error

- src/seer/automation/agent/agent.py
- src/seer/automation/agent/client.py
- src/seer/langfuse.py
Langfuse automatically flushes in the background. Correct me if I'm wrong, but I don't think we ever force terminate the program and would lose any data by relying on the automatic flushes.
These manual flushes block the main program and add ~750ms-1s of cold start on every LLM call, every keyword search, and every missing file fixer. (some profiles showed it taking up to 10s sometimes) Langfuse officially says to only use this when necessary as it is known to hurt performance.
So this would be a nice improvement to snappiness if we can get away with it.
> fix(autofix): Remove langfuse flushes to reduce cold starts

- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- src/seer/anomaly_detection/detectors/mp_scorers.py
- tests/seer/anomaly_detection/detectors/test_mp_scorers.py
- tests/seer/anomaly_detection/test_anomaly_detection.py
- tests/seer/anomaly_detection/test_utils.py
This change aborts saving data if the batch detection takes too long. This will help reduce the instances when Seer data goes out of sync with alerting system.
With this implementation, both `store_data` and `detect_anomalies` APIs return 500 - server error if the detection takes longer than 4.5 mins.
> chore(anomaly-detection): do not store data if operation takes too long

- src/seer/anomaly_detection/tasks.py
- Force stumpy compilation (specifically for the `aamp` and `aampi` objects) through a dummy call before the more expensive call from the cleanup occurs
- Fixes the cold start issues from the cleanup because the `_compute_matrix_profile` function should no longer take large amounts of time due to forced compilation
> chore(anomaly detection): Force stumpy compilation

- src/celery_app/app.py
Celery's `on_configure` is called to configure the "celery app" instance, this includes when you need to intialize it to send a task. This means that when we were submitting a task, such as through `apply_async` **we were actually calling `bootup` again.**
This is fixed by moving the bootup calls for both the celery worker and celerybeat to its own init signal handlers
Fixes [SEER-9P](https://sentry.sentry.io/issues/5731122470/)
----
This issue was able to be reproduced locally by simulating _multiple instances of seer_ locally, then in the logs it was clear that when we were scheduling the task, the _bootup_ call was being called from wherever the task was being scheduled from, **not** from the forked worker process like we thought. Although I didn't get the SQLAlchemy error like in …
> fix(seer): Fix multiple bootup problem

- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/coding/models.py
- src/seer/automation/autofix/components/coding/prompts.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/components/root_cause/prompts.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/prompts.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/models.py
- tests/automation/autofix/test_models.py
- tests/automation/test_automation_models.py
Allow a profile to be passed into the Autofix request and add a map of code execution to the initial prompt.
Uses the stack trace to filter the map to the relevant section, with some extra context before and after. This should keep things from going out of control.
For example, if we have an error in `scrub_pii`, we'll tell Autofix: "Here's a partial map of the code at the time of the issue":
```
...
→ RepoClient.__init__ (seer/automation/codebase/repo_client.py)
→ get_github_app_auth_and_installation (seer/automation/codebase/repo_client.py)
→ RepoClient.get_default_branch_head_sha (seer/automation/codebase/repo_client.py)
→ RepoClient.get_branch_head_sha (seer/automation/codebase/repo_client.py)
→ RepoClient.get_valid_file_paths (seer/automation/codebase/repo_client.py)
→ …
```
> feat(autofix): Support profiles as context

- src/seer/automation/autofix/tools.py
- src/seer/automation/codebase/code_search.py
- tests/automation/codebase/test_code_search.py
Sometimes the code context returned by keyword search would be really long (usually when there was a ton of code on one line, like some js core bundles), causing the LLM to error out. This PR limits each piece of context to 2000 characters.
NOTE: waiting on security issue to be resolved before I push working cassettes
> fix(autofix): Truncate long keyword search context

- src/seer/json_api.py
- tests/test_json_api.py
_Previously request signing was disabled due to a quirk in our networking setup that made the request url passed to the client signer not the same as the request seen on the server side._
This reimplements the request signing with an optional nonce but without the salted url verification. This is a stop-gap measure to reimplement signature signing for now until we have bandwidth to invest in a more complete solution.
> fix(api): Reintroduce request signing

- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- tests/seer/anomaly_detection/test_anomaly_detection.py
Some of the detection calls from the UI are taking too long. This PR adds timeout for stream detection of multiple timesteps to address.
> chore(anomaly-detection): add timeout for calls from UI that include both batch and stream computation

- src/seer/automation/autofix/components/comment_thread.py
Make the action detection behave more naturally.
> fix(autofix): Update action detection prompt in comment thread

- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- tests/automation/autofix/test_autofix_event_manager.py
When rethinking, we just clear the file changes if there is no more changes step.
Tested locally to ensure fully working.
Fixes #1465
> fix(autofix): Clear file changes on step reset without changes

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/steps/change_describer_step.py
- src/seer/automation/autofix/tasks.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/autofix/test_autofix_tasks.py
- tests/automation/autofix/test_models.py
- tests/data/autofix_full_finished_run.json
- tests/data/autofix_root_cause_run.json
Remove unused `repo_id` and `namespace_id` from the codebase indexing days, we now use `repo_external_id`
> ref(autofix): remove repo_id and namespace_id

- src/seer/automation/agent/client.py
The client [retries](https://github.com/openai/openai-python/blob/d16e6edde5a155626910b5758a0b939bfedb9ced/src/openai/_base_client.py#L723-L726) on APITimeoutErrors. The timeout for issue summary is [7 seconds](https://github.com/getsentry/seer/blob/c504fcbc506585b65cd548dbf75ea96f90fee558/src/seer/automation/summarize/issue.py#L88).
> fix(issue summary) Increase OpenAI max_retries from 2 to 4

- src/seer/automation/autofix/components/insight_sharing/component.py
Weird hallucinations would happen if the insight card prompt didn't contain any input.
> fix(autofix): Handle empty thoughts in insight sharing

- src/seer/automation/agent/client.py
- src/seer/automation/autofix/evaluations.py
- src/seer/automation/autofix/tasks.py
- tests/automation/autofix/test_autofix_evaluations.py
o3 mini for scoring, + new prompt for root cause that should fix issues that we were seeing such as
- Mistaking the expected for the predicted
- Not being critical enough of the root cause
- Being _too strict_ 
Also adds a new metric for how helpful it is
> feat(autofix-evals): o3-mini for evals + rca eval scorer prompt

- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/coding/models.py
- src/seer/automation/autofix/components/coding/prompts.py
- src/seer/automation/autofix/components/insight_sharing/component.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/steps/coding_step.py
- src/seer/automation/autofix/tasks.py
The coding step can be invoked with options to just write a fix, to just write a repro test, or both. It defaults to just a fix.
Evals are stable between writing a fix and writing a fix with a test.
This PR should go in before the frontend change.
> feat(autofix): Add unit test options to coding step

- requirements.txt
- src/seer/automation/agent/client.py
- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/is_root_cause_obvious.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/components/solution/component.py
- src/seer/automation/autofix/components/solution/models.py
- tests/automation/autofix/test_autofix_tasks.py
Replaces all uses of 4o mini in Autofix with Flash 2.0. This means short circuiters and formatters. Cut 45 seconds off run time, improved root cause eval from 80 to 84%, but dropped fix eval from 39% to 35%.
> chore(autofix): Replace 4o mini with Flash 2

- .env.example
- README.md
- docker-compose.yml
If you set unique ports for each version of seer, docker compose should just work.
> devenv: Allow multiple seers to run at the same time

- .github/workflows/tests.yml
- docker-compose.ci.yml
- docker-compose.yml
- gocd/templates/bash/check-github.sh
1. Parallelizes the tests using `pytest-split`
2. Uses a single build and push command for the docker image, then pulls it for every other job instead of calling Buildx every time
3. Points GoCD to look at the new parallelized tests check
**_Reduces total CI runtime from ~20 minutes to ~5 minutes._** This will also have the same effect on _deploy_ times!
> build(ci): Parallelize tests and optimize image building

- src/seer/automation/agent/client.py
- tests/automation/autofix/test_retry_stream.py
Updates the 429 error for Gemini to the one based on the [Sentry issue](https://sentry.sentry.io/issues/6301072208).
My previous guess for the shape of this error was based on [this message in the docs](https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429), but that message has [never been encountered](https://console.cloud.google.com/logs/query;query=labels.%22k8s-pod%2Fenvironment%22%3D%22autofix%22%0A%2528%0A%20%20%20%20--%20%2528SEARCH%2528%22APIStatusError%22%2529%20AND%20severity%3D%22ERROR%22%2529%20%20--%20Anthropic%0A%20%20%20%20%2528SEARCH%2528%22ResourceExhausted%22%2529%20AND%20severity%3D%22ERROR%22%2529%20%20--%20Gemini%0A%20%20%20%20--%20%2528SEARCH%2528%22MaxTriesExceeded%22%2529%20AND%20severity%3D%22ERROR%22%2529%0A%20%20%20%20--%20OR%20%2528SEARCH%2528%22 …
> fix(autofix) Retry Gemini 429

- src/seer/automation/autofix/components/coding/component.py
Occasionally, the apply model would not complete its response with a `</updated_code>` tag or it would be truncated for some other reason, causing the "new content" to be empty and cause the whole file to be deleted.
Now if there is no new content from the apply model (meaning something went wrong), fall back to asking Gemini Flash to directly write a unified diff. (I tested always just writing a diff, but the fix accuracy went down, so just using it as a fallback).
> fix(autofix): Add fallback for code application step

- .github/workflows/cleanup.yml
Cron job that runs every day at 18:00 UTC (10am PT) to clean up cached build containers **_older than 14 days._** Regardless of date, we will keep a minimum of 16 containers.
> chore(ci): Container registry cache cleanup

- src/seer/automation/codebase/code_search.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/codebase/utils.py
- src/seer/automation/utils.py
We're getting a good amount of errors decoding files: https://sentry.sentry.io/issues/6183118961/
It's mostly because of: 
1. Detecting the wrong encoding. So let's only choose a new encoding if we're confident.
2. The agent was trying to read images and other invalid files because we showed them to it in some tools. So let's exclude these unsupported files.
> fix(autofix): Stricter threshold for detected encodings

- src/seer/automation/autofix/evaluations.py
An issue with the prior prompt was that we were having it overfocus on scoring how well the predicted solution "matches" an expected output, rather than scoring how well the issue is fixed.
This prompt update:
1. Changes the concept of an "expected" solution to a "known" solution and prompts o3-mini to use it to inform what the issue was
2. The score is now on how well the predicted solution fixes the issue rather than asking it to score how well it "matches"
3. Prompt format adjustment to place context at the end for reasoning models.
(ignore the latency, i was running multiple evals at the same time so it slowed)
> chore(evals): Improve final fix scoring prompt

- src/seer/automation/agent/client.py
- src/seer/automation/autofix/components/root_cause/component.py
Gemini can return a structured output where `completion.parsed is None`. These are handled by downstream uses of `generate_structured`, and retrying adds some latency. But it's probably worth it if it means getting an output.
> fix(autofix) Retry null Gemini structured outputs

- src/seer/automation/codegen/relevant_warnings_step.py
The overwatch payload expects the json serialization to exclude spaces e.g. like `{"run_id":"test-123"}` not `{"run_id": "test-123"` (note the space before "test-123") and since the exact string needs to match when signed with the shared secret, need to add this extra serialization rule
> fix(relevant-warnings): Fix serialization on overwatch payload

- src/seer/automation/agent/client.py
- src/seer/automation/agent/models.py
- src/seer/automation/autofix/autofix_agent.py
- tests/automation/agent/test_client.py
- tests/automation/autofix/test_autofix_agent.py
Autofix run timeouts turns out happens (so far as we know) on 2 reasons:
1. A deploy goes out and kills the run
2. Streams hanging, especially from anthropic
This PR fixes the latter stream hanging issue by introducing a time to first token timeout and a stream inactivity timeout.
> fix(autofix): Timeout + retry on stream first token and hanging

- gocd/templates/bash/run-migrations.sh
- src/seer/configuration.py
- src/seer/db.py
- Uses `DATABASE_MIGRATION_URL` if present which includes the proper permissions for creating migrations
- Defaults to the standard `DATABASE_URL` otherwise
> chore(seer): Use Migration URL

- src/seer/automation/autofix/evaluations.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/tasks.py
- tests/automation/autofix/test_autofix_evaluations.py
The solution eval now tests the fix on the solution step, while the coding step we have a new `correctness_score` and a `conciseness_score` that just tests how well it takes its instructions and writes code for it.
This also removes the `run_type` field from the evaluation call and the individual root cause and coding evals, this is because we weren't using the other ones. They were outdated deadcode. We can just quickly write them up again when we were using it.
> feat(autofix-evals): Separate solution & coding evals

- src/seer/anomaly_detection/detectors/mp_boxcox_scorer.py
- tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py
- Speeds up threshold recovery from a large spike by using the latter half of the calculated MP Distances during the boxcox threshold calculation
- 28 days of data is still used to calculate the matrix profiles ensuring the full history is used, but only 14 days worth of MP Distances are used for the ultimate calculation
> chore(anomaly detection): Speedup Threshold Recovery

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/evaluations.py
- src/seer/automation/autofix/tools.py
- src/seer/automation/codebase/repo_client.py
- tests/automation/autofix/test_autofix_tools.py
- tests/automation/codebase/test_repo_client.py
Adds two new tools:
- Explain File: given a file, show the descriptions of the 30 most recent commits as well as a tree of what other files were touched in the same commit.
- View Diff: given a 7-char commit sha and a specific file, view the diff of the change made.
Both tools typically complete in 2-5s. I think the latency increase in the evals is because the agent decides to explore more files after seeing the connected files, which also leads to better solutions.
Eval results:
- Root cause stable
- Solution correctness: 55% -> 62%
- Code conciseness: 91% -> 95%
- Code correctness: 86% -> 88%
> feat(autofix): Add tools for commit history

- src/seer/anomaly_detection/tasks.py
- tests/seer/anomaly_detection/test_cleanup_and_predict_tasks.py
- Changes the store query to be an upsert so we can include all the new predictions
- Update test to ensure timestamps do not include seconds as in production
> fix(anomaly detection): Change Store Query to Upsert

- src/seer/automation/codegen/relevant_warnings_component.py
- src/seer/automation/models.py
- tests/automation/autofix/test_models.py
- tests/automation/codegen/test_relevant_warnings.py
When fetching issues matching file patches in sentry, we look up the repo (sentry object) by its uniqueness constraint. Need the raw, un[processed](https://github.com/getsentry/seer/blob/108d9a7686a43b4ff062ea322f2eb74b4e3c29cc/src/seer/automation/utils.py#L107-L110)/unstripped provider to do that.
> fix(relevant-warnings) Add raw provider field

- src/seer/automation/codegen/models.py
- src/seer/automation/codegen/relevant_warnings_component.py
- src/seer/automation/codegen/relevant_warnings_step.py
- tests/automation/codegen/test_relevant_warnings.py
Overwatch runs static analysis on the whole project every commit and sends these warnings to seer. Currently, the warning paths may not be normalized to the repo root. So need to do some fuzzy matching for now
> fix(relevant-warnings) Filter warnings from files not affected by commit

- requirements.txt
- src/seer/anomaly_detection/detectors/mp_boxcox_scorer.py
Storing NaN in DB results in redash issues. So switching to a low float value instead.
> chore(anomaly_detection): avoid NaNs in scores

- tests/seer/anomaly_detection/test_cleanup_and_predict_tasks.py
- Coordinate timestamps so that predictions and what is in the database are aligned and do not desync when predictions are being upserted into db
- Previously, test would flake because timestamps created right near the end of the minute would not be synced with values being pushed into the table right after the minute. Therefore, records would be off by 1 minute and would insert all the new values rather than updating because of the time desync
> fix(anomaly detection): Coordinate Prophet Test Timestamps

- src/seer/automation/autofix/components/coding/utils.py
- src/seer/automation/autofix/utils.py
- tests/automation/autofix/test_autofix_utils.py
This hopefully fixes the issue where the diff application looks completely glitched. My hypothesis from the examples I looked at was that it was replacing snippets in the wrong location, so a stricter matching process should fix it. This is also ok because our diff output from the coding step is nearly perfect in accuracy, so we don't need to be as "fuzzy" as we used to.
> fix(autofix): Stricter fuzzy matcher for more reliable diff application

- src/seer/automation/autofix/components/coding/prompts.py
- src/seer/automation/autofix/components/solution/models.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/steps/coding_step.py
- tests/automation/autofix/test_autofix_event_manager.py
Le coding agent will follow the solution passed from the UI, and we also store which is active or not
Key change is on the update call, the frontend can pass a solution to be set
Custom solution is removed on frontend, keeping it here for backwards compat
> feat(autofix): Coding follows a solution from UI

- src/seer/automation/codegen/models.py
- src/seer/automation/codegen/relevant_warnings_component.py
- src/seer/automation/codegen/relevant_warnings_step.py
- tests/automation/codegen/test_relevant_warnings.py
[context in slack](https://sentry.slack.com/archives/C08B43VDQVD/p1741312266930079)
> fix(relevant-warnings) Read PR instead of commit

- src/seer/automation/codegen/relevant_warnings_component.py
- tests/automation/codegen/test_relevant_warnings.py
I forgot that the Sentry/Seer RPC method can return an empty dict if it doesn't find any projects, a language parser, or function names for any PR files
fix https://sentry.sentry.io/issues/6382411120
> fix(relevant-warnings) Handle no issues found

- src/seer/anomaly_detection/accessors.py
- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- src/seer/anomaly_detection/detectors/anomaly_scorer.py
- src/seer/anomaly_detection/detectors/mp_boxcox_scorer.py
- src/seer/anomaly_detection/detectors/mp_scorers.py
- src/seer/anomaly_detection/models/__init__.py
- src/seer/anomaly_detection/models/timeseries_anomalies.py
- tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py
- tests/seer/anomaly_detection/detectors/test_anomaly_scorer.py
- tests/seer/anomaly_detection/models/test_timeseries.py
- tests/seer/anomaly_detection/models/test_timeseries_anomalies.py
- tests/seer/anomaly_detection/test_accessors.py
- tests/seer/anomaly_detection/test_anomaly_detection.py
- tests/seer/anomaly_detection/test_cleanup_and_predict_tasks.py
- Adjusts the scoring algorithm to use the MP Flags if there is strong confidence (mp_dist > 2 * threshold) even if prophet does not indicate an anomaly. This is an incremental change.
Before MP Override:
After MP Override:
If we look at the end of the big spike in this example, because the Prophet CI begins to widen after, originally we stop the alert earlier than we should (not good in stream case where we are not sure how the timeseries will behave next). By adding the override, we extend the anomaly just a little more and ensure we are fully confident before marking it as resolved. 
Overall in the other examples, only 1 of them produced a 1 timestep false positive while the rest remained the same as intended.
**CAVEAT:**
An example like this still needs to be dug deeper into because …
> feat(anomaly detection): MP Override

- src/seer/automation/codegen/relevant_warnings_component.py
issue details can be quite large and it's not critical to get lots of cache hits
> fix(relevant-warnings) Reduce issue cache max size

- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/models.py
Creates a model for trace data for the `sentry` backend to send. Also passes it into the root cause request, but doesn't use it, so I can inspect Langfuse logs to see the data looks right in prod before putting it in a prompt. It does include the transaction name in the event details that go in our prompts though.
Once I can confirm this is working in prod, my plan is to follow up with using this in our prompts and adding related tools.
> feat(autofix): Receive trace tree in request payload

- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/coding/prompts.py
- src/seer/automation/autofix/components/solution/models.py
- src/seer/automation/autofix/event_manager.py
Always adds a step to add a unit test at the end of the solution timeline, but disables it by default. Adds support for triggering "testing mode" if that event is present in the solution sent in the payload. I tested it and it follows instructions nicely.
> feat(autofix): New testing flow

- src/seer/anomaly_detection/accessors.py
- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- src/seer/anomaly_detection/detectors/anomaly_scorer.py
- src/seer/anomaly_detection/detectors/prophet_anomaly_detector.py
- src/seer/anomaly_detection/detectors/smoothers.py
- src/seer/anomaly_detection/models/algo_config.py
This PR includes:
* reducing the number of days use stream prediction to 3 days
* changes the number of prophet predictions to cover all 3 days to reduce the number of times we run Prophet prediction
* removes trace on methods that are called for each point in the dataset to avoid huge traces
> bugfix(anomaly detection): fix for combined detection call from UI timing out

- src/seer/automation/codebase/repo_client.py
After looking at the trace of a lot of the errors, [a lot of them are coming from the non-draft pr line](https://sentry.sentry.io/issues/6361334163/events/f3e7f38368fa449aba774b4fa940d9fa/?project=6178942&sort=date&statsPeriod=14d). And apart from that the errors don't have a stacktrace, this attempts to better logging there so we can debug what the actual issue is.
Also, if a PR already exists for a branch, we should just return it and link to it on Autofix cuz u can only have 1 PR for a branch...
> fix(autofix): Return existing PR + logging

- src/seer/automation/autofix/components/confidence.py
- src/seer/automation/autofix/steps/coding_step.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/autofix/steps/solution_step.py
- tests/automation/autofix/components/test_confidence.py
- tests/automation/autofix/steps/test_root_cause_step.py
should be more of a question now
> fix(autofix): Update Q&A prompt

- src/seer/automation/codebase/repo_client.py
When getting pull requests, github expects a wildly different ref format
https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests
> fix(autofix): Fix get pulls

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/codebase/models.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/summarize/issue.py
- src/seer/automation/utils.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/codegen/test_relevant_warnings.py
- tests/automation/summarize/test_issue.py
From https://github.com/codecov/overwatch/pull/239 we will be able to have code snippets for the warnings. The hope is that they will help provide better suggestions from the LLMs.
Obviously depends on that PR being merged.
I did spent more time than I expected fixing the formatting, not sure if it was all that worth it. Do LLMs even care?
> :alien: add code snippet to StaticAnalysisWarning

- .github/workflows/relevant-warnings.yml
- src/seer/automation/codegen/models.py
- src/seer/automation/codegen/relevant_warnings_component.py
- src/seer/automation/codegen/relevant_warnings_step.py
- tests/automation/codegen/test_relevant_warnings.py
Filter warnings based on those that have a line number in the modified file line numbers in the PR diff. Previously we allowed the warning to exist anywhere in the same file, which turned out to be too loose.
Closes https://github.com/codecov/overwatch/issues/242
> fix(relevant-warnings): Filter warnings by pr diff instead of by files

- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/tasks.py
- tests/automation/autofix/test_autofix_tasks.py
Adds `solution_thumbs_up` and `solution_thumbs_down` to `AutofixFeedback`
> feat(autofix): Add solution thumbs up / down

- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/root_cause/prompts.py
- src/seer/automation/autofix/components/solution/component.py
- src/seer/automation/autofix/components/solution/models.py
- src/seer/automation/autofix/components/solution/prompts.py
- src/seer/automation/autofix/prompts.py
- src/seer/automation/autofix/steps/solution_step.py
- src/seer/automation/autofix/tools.py
- src/seer/automation/models.py
- tests/automation/test_automation_models.py
- Adds trace tree to root cause and solution prompts
- Adds two tools to fetch profiles, spans, and connected errors 
Both are gated just to @roaga (me) for now.
> feat(autofix): Add trace context to prompts and offer tools

- src/seer/anomaly_detection/accessors.py
- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/detectors/anomaly_detectors.py
- tests/seer/anomaly_detection/detectors/test_anomaly_detectors.py
- There could be cases when MP in the past said there is an alert (but not high confidence enough to force an alert) and prophet does not agree, so no alert fires.
-  However, due to smoothing incorrectly being applied to the MP original flags, an alert could still be fired on non-anomalous data (neither algorithm agreeing), because there would be a majority of the MP original flag, not the `combined original flags`
- Uses the `algorithm_type` (the enum which indicates which combination of the two algorithms cause the alert) to determine the `combined_original_flag`
> fix(anomaly detection): Fix Ghost Alerts

- src/seer/automation/autofix/tools.py
- tests/automation/autofix/test_autofix_tools.py
Disabling shell for the `grep` and `find` tools for security purposes.
Also make `list_directory` return a `tree` format of nested directories.
Root cause correctness went from 84 to 88%.
Solution correctness went from 67% to 68%.
> feat(autofix): Disable shell for command tools, make list directory a tree

- src/seer/app.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/codegen/tasks.py
- src/seer/automation/codegen/unit_test_coding_component.py
- src/seer/automation/codegen/unittest_step.py
- tests/automation/codegen/test_unit_test_step.py
If the invocation is from a Codecov service, use the codecov GH app to post unit tests to a PR. This will enable the `retry-unit-test` flow automatically going forward for codecov unit test requests.
> Add GH app logic to unit test endpoint

- src/seer/automation/summarize/issue.py
- tests/automation/summarize/test_issue.py
possible causes aren't showing up b/c the confidence and novelty scores are nullified, and the [thresholding logic in the frontend](https://github.com/getsentry/sentry/blob/6094a746573f63cb425f2c6bb70500a5b729188f/static/app/components/group/groupSummary.tsx#L196-L201) defaults to not showing the cause if either are null
> fix(issue-summary) Keep scores when scoring autofixability

- src/seer/anomaly_detection/detectors/anomaly_scorer.py
- tests/seer/anomaly_detection/detectors/test_anomaly_scorer.py
- Disable MP for now as missing data can cause the MP to perform erratically and force override when not necessary
> chore(anomaly detection): Disable MP Override

- .env.example
- Set 'DD_DOGSTATSD_DISABLE` = `True` for local development 
- datadog initialize automatically picks this up (https://github.com/DataDog/datadogpy?tab=readme-ov-file)
> chore(seer): Disable datadog for local dev

- src/seer/automation/summarize/issue.py
Sometimes we're crossing the input token limit. So when we do, this retries one more time by removing the code context, variable context, and breadcrumbs from trace-connected issues.
> fix(issue summary): Retry issue summary with less context if crosses limit

- src/seer/automation/codegen/models.py
We send over a `str:str` key, value pair from Codecov. Tests already expect this value and so does logic in `RetryUnitTestStep`
> [fix] Fix type error in CodegenBaseRequest

- src/seer/automation/autofix/runs.py
we were accidentally clearing repos if no preference was set, which broke evals.
> fix(autofix): Fix accessible repos in evals

- src/seer/automation/autofix/tools.py
- src/seer/automation/codebase/repo_client.py
- tests/automation/codebase/test_repo_client.py
When getting a git tree, if the result from the GitHub API is truncated, recursively get the subtrees of the main tree's directories until we have a complete tree. Since this is done in parallel, it's pretty fast. On Seer, a non-truncated call is ~1.2s and this recursive approach is ~3s. On getsentry, it was ~1s and ~2.5s.
> fix(autofix): Handle truncated repos

- src/seer/automation/autofix/tasks.py
The memory key was wrong, so the memory was always missing for all comments on the plan+code step.
> fix(autofix): Fix missing memory on coding step comment threads

- src/seer/automation/autofix/tasks.py
It would be really awkward if you had a manual run overwritten by an automatically-triggered run. Or if multiple auto-runs were happening at once.
The sentry-side check is already there, but it could still be bypassed with the network delay and the snuba querying delays.
> chore(autofix): Prevent auto runs from overwriting existing runs

- .github/workflows/tests.yml
`pytest-split` was creating a split with an empty group, causing our CI to fail in PR #2329 
Fix as mentioned in the issue on `pytest-split`'s repo: https://github.com/jerry-git/pytest-split/issues/95 is to change the splitting algorithm.
> fix(ci): Use pytest-split's least-duration algo

- src/seer/automation/agent/client.py
- src/seer/automation/agent/models.py
We'll need to update our langfuse instances to v3 to correctly account for cached tokens, which needs us to set up clickhouse.
Instead, this as an interim half-solution is to include all cached tokens as prompt tokens.
This won't fully fix it but at least it gets us in the ballpark of what the scale of what it does cost us vs not including any of those tokens at all.
> fix(langfuse): Count all prompt cache tokens as prompt tokens

- src/seer/app.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/tasks.py
Makes the PR creation task set the Autofix state and not wait for a timeout (the task still has a 60 second timeout). This is so the frontend can poll for it. This approach should be more stable and avoid random connection issues.
> fix(autofix): Make PR creation task pollable

- src/seer/automation/summarize/issue.py
- src/seer/inference_models.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/summarize/test_issue.py
- tests/test_seer.py
added quite a bit more data. see [the notebook](https://github.com/getsentry/data-analysis/blob/main/autofix/issue_summary/autofixability/train.ipynb). main difference is that precision is around +10-15% higher for the top 10% of fixability scores. also looks cleaner, qualitatively
> fix(issue-summary) Fixability more finetuned

- pyproject.toml
We were getting this issue while building:
```
× Preparing metadata (pyproject.toml) did not run successfully.
3.153   │ exit code: 1
3.153   ╰─> [11 lines of output]
3.153       running dist_info
3.153       creating /tmp/pip-modern-metadata-i8f_l1xh/seer.egg-info
3.153       writing /tmp/pip-modern-metadata-i8f_l1xh/seer.egg-info/PKG-INFO
3.153       writing dependency_links to /tmp/pip-modern-metadata-i8f_l1xh/seer.egg-info/dependency_links.txt
3.153       writing requirements to /tmp/pip-modern-metadata-i8f_l1xh/seer.egg-info/requires.txt
3.153       writing top-level names to /tmp/pip-modern-metadata-i8f_l1xh/seer.egg-info/top_level.txt
3.153       writing manifest file '/tmp/pip-modern-metadata-i8f_l1xh/seer.egg-info/SOURCES.txt'
3.153       reading manifest file …
```
> fix(ci): Force Wheel version

- docker-compose.yml
- src/seer/automation/agent/client.py
- src/seer/bootup.py
- src/seer/configuration.py
`SENTRY_REGION` is already set in all the seers in prod via https://github.com/getsentry/ops/pull/14607
(The AppConfig setup will fail the deploy if this var is not actually set)
> ref: Use SENTRY_REGION instead of USE_EU_REGION

- src/seer/automation/codebase/models.py
- src/seer/automation/codegen/codegen_event_manager.py
- src/seer/automation/codegen/models.py
- src/seer/automation/codegen/prompts.py
- src/seer/automation/codegen/relevant_warnings_component.py
- src/seer/automation/codegen/relevant_warnings_step.py
- tests/automation/codegen/test_relevant_warnings.py
Significant changes to the Relevant Warnings Step so that we suggestions are better.
* Don't require warning _and_ issue to exist
* Add diff to the analysis
* Change prompt to _predict_ potential issues
This is a significant change to the relevant warnings step. It moves somewhat away from the warnings as the sole main focus, and kinda equally use warnings and issues as extra context for the LLM to evaluate the PR dif.
It changes several smaller LLM calls (that decide if warnings and issues can be paired logically) by 1 bigger one (that analyses the entire diff). Works well for small diffs and a small number of warnings and issues, but we're not very sure the scaling factor here.
The next steps would be to better limit the size of the diff, or break it up into different chunks and analyze …
> change relevant warnings prediction

- README.md
- src/seer/automation/autofix/tasks.py
Moves the scoring calls outside the main eval item observation context manager. This is part of fixing the bug we saw where we had nested eval runs.
The 2nd part of that is we **NEED** to run each eval run with a unique name, even if you deleted the previous one
> fix(autofix-evals): move score outside observation

- src/seer/automation/codegen/models.py
- tests/automation/codegen/test_relevant_warnings.py
Structured output respects order, so will probably get better confidence scores if the missing evidence is generated before confidence. Missed this minor thing during review.
> fix(relevant-warnings) Order evidence before confidence

- src/seer/automation/codebase/models.py
- src/seer/automation/codegen/models.py
- src/seer/automation/codegen/prompts.py
- src/seer/automation/codegen/relevant_warnings_component.py
- src/seer/automation/codegen/relevant_warnings_step.py
- src/seer/automation/models.py
- tests/automation/codegen/test_relevant_warnings.py
- tests/automation/test_automation_models.py
Here's an [example of a prompt](https://github.com/getsentry/data-analysis/blob/main/error_prevention/relevant_warnings/prompt.txt) w/ embedded warnings ([for this dummy PR](https://github.com/getsentry/seer/pull/2406) and dummy warnings)
The annotations are in `<-- STATIC ANALYSIS WARNINGS`
> feat(relevant-warnings) Embed warnings into diff

- src/seer/automation/codegen/prompts.py
- src/seer/automation/codegen/relevant_warnings_component.py
- tests/automation/codegen/test_relevant_warnings.py
The prompt asks for step-by-step thinking, but the output is immediately the list of suggestions. When using structured output, need to explicitly add in a section for thinking (unless it's a reasoning model, which flash 2.0 is not). I missed this during review
> fix(relevant-warnings) Add analysis section

- src/seer/automation/autofix/autofix_agent.py
Before: cleared the user-facing output stream whenever we started a new stream
After: clear the user-facing output stream whenever we start a new stream AND the new stream has text in it
This handle no token streams from Gemini causing a bad UX.
> fix(autofix): only clear stream if there is content in the new stream

- src/seer/automation/autofix/tools.py
- tests/automation/autofix/test_autofix_tools.py
Common failure mode for the grep tool is the agent tried to grep a directory but forgets the `-r` flag. Just catching that and auto-retrying to save iterations here.
> fix(autofix): autocorrect grep command if simply missing -r flag

- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/solution/component.py
- src/seer/automation/autofix/tools/semantic_search.py
- src/seer/automation/autofix/tools/tools.py
- src/seer/automation/codegen/pr_review_coding_component.py
- src/seer/automation/codegen/retry_unittest_coding_component.py
- src/seer/automation/codegen/unit_test_coding_component.py
- tests/automation/autofix/test_autofix_tools.py
The old semantic search tool was pretty hit-or-miss, and completely broke on big repos. Replacing it with a small gemini flash agent that can use `tree` and `expand_document` to find the exact answer to the query. In some examples on `sentry` it could find most things within 10 seconds.
Bumps solution score to ~61%, cuts latency and cost further from last eval (though that could be the broken evals).
> feat(autofix): New semantic search tool

- src/seer/automation/autofix/components/coding/component.py
Should be more reliable after looking at the logs of the eval run it looks like less overloaded errors?
No difference in coding eval:
> fix(autofix): Downgrade coding to 3.5 sonnet v2

- src/seer/automation/summarize/issue.py
Currently, most fixability invocations are on our org's issues, which have a lower fixability rate than the test set used to derive the current threshold.
Can reset this back before launch. Would like to stretch it out a bit for now for better dogfooding / to see more potential failure cases
> fix(fixability) Lower thresh further for dogfooding

- src/seer/anomaly_detection/detectors/anomaly_detectors.py
Removing the redundant init code in MPBatchAnomalyDetector that sometimes takes up about 100 ms.
> chore(anomaly_detection): reduce MPBatchAnomalyDetector init time

- src/seer/automation/codebase/repo_client.py
- tests/automation/codebase/test_repo_client.py
Fix for https://github.com/getsentry/seer/security/code-scanning/19.
> security: fix tarfile extraction

- .github/workflows/cleanup.yml
- .github/workflows/linting.yml
- .github/workflows/relevant-warnings.yml
- .github/workflows/tests.yml
- .github/workflows/validate-pipelines.yml
Using version tags or no specifier at all can open us up to dependency attacks.
Pinning the SHA is a strong mitigation. 
See: https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
> gha: pin action versions

- src/seer/automation/autofix/tools/tools.py
- tests/automation/autofix/test_autofix_tools.py
`_get_repo_name_and_path` was erroring on the create action because it didn't allow nonexistent paths which are needed by the create tool and potentially the undo tool.
> fix(autofix): Fix claude create tool

- src/seer/automation/agent/client.py
Sometimes Claude would think, but then return no content. This change should catch that case and properly retry without adding the blank stream to memory and breaking the run.
> fix(autofix): Handle claude giving no content after thinking

- src/seer/automation/autofix/tools/tools.py
Tweaks to address common Claude coding tools failures that were leading to more iterations than necessary.
- handle leading slashes in paths
- handle claude messing up indentation by giving it a better error message
> fix(autofix): Handle some claude tools faillures

- src/seer/automation/autofix/autofix_agent.py
In some edge cases, autofix will call hundreds of tools at once and cause run timeouts. So this rejects any tool calls after the first 3 in the same iteration. The reason we still have to add the rejections to memory is so Claude API doesn't complain.
> fix(autofix): Limit parallel tool calls

- gocd/templates/bash/deploy.sh
- gocd/templates/bash/run-migrations.sh
1. We weren't actually deploying normal `seer` to customer 4
2. On customer 4 normal `seer` exists now so we can use it for migrations and not `seer-gpu`
> ci(st): Fix deploys for customer 4

- src/seer/automation/codebase/repo_client.py
- tests/automation/codebase/test_repo_client.py
We were supposed to be passing a `SHA1` type [tree object sha](https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28#get-a-tree) to the tree endpoint not the commit sha. I'm not sure how it worked before when we were passing the commit sha though, maybe they were unraveling it for us as a convenience/fallback?
ChatGPT o3 is saying GitHub rolled back the unravelling earlier this year but didn't provide a source, could be hallucinating.
Regardless, we should fix this bug.
> fix(autofix): Fix using commit sha in tree sha

- src/seer/automation/autofix/tools/tools.py
- src/seer/automation/codebase/repo_client.py
o3 suggested that the undocumented `repositories/:id` endpoint is not whitelisted for github app installations? This will try to use the full name before using the id.
- fixes a trace for repo downloading
- adds spans for the repo metadata read call
> fix(autofix): Attempt fix for repo metadata read

- src/celery_app/config.py
We found that both in local eval runs and in prod, memory gradually adds up on all autofix pods until a deploy happens. This means there's some memory leak in Autofix.
This setting to celery makes each child process of a celery worker only accept 3 tasks before being recreated, freeing memory.
This is a stopgap until we find the source of the memory leak, but we should be refreshing our celery workers anyways.
> fix(autofix): Set celery max tasks per child

- src/seer/automation/autofix/components/root_cause/component.py
- src/seer/automation/autofix/components/solution/component.py
For the context gathering step in the root cause and solution, switches the temperature from 1.0 (remnant from claude thinking) to 0.0. Seems to improve evals slightly by a few points.
> fix(autofix): Set temp to 0 for gemini flash

- src/celery_app/config.py
- src/seer/automation/codebase/repo_client.py
Turns out the memory leak we had in Autofix was due to us misusing `functools.cache`/`functools.lru_cache`. When it caches the arguments it caches _all_ the arguments. **This includes the instance of `self`** This means that we were maintaining a reference to instances of the repo client in this case as long as the cache persisted and if the instance isn't the exact same one we weren't even getting cache hits.
Before:
After:
(this also probably means Autofixes are slightly faster because we'll now be getting cache hits!)
To correctly use the cache on class instance methods you have to pass the "de-selfed" version within the constructor. 
Note: You can safely cache class methods because the `cls` instance is consistent.
> fix(autofix): Fix memory leak due to functools caches

- src/seer/automation/autofix/tools/read_file_contents.py
- src/seer/automation/autofix/tools/tools.py
- tests/automation/autofix/test_autofix_tools.py
- tests/seer/automation/autofix/tools/test_read_file_contents.py
We often get 404 errors from Github when reading files, when that happens, let's try reading the file locally that has better logging/error states
> fix(autofix): Fallback to local file reading if expand document fails

- src/seer/automation/autofix/tools/ripgrep_search.py
- src/seer/automation/autofix/tools/tools.py
- tests/test_ripgrep_search.py
1. Add `fixed_strings` as an option to ripgrep as another search option
2. Better responses to show the command to the LLM for debugging purposes
3. Add logging in failure cases to `ls` the repo and the types
4. Bumps ripgrep threads to 2
> feat(autofix): Better ripgrep option, response, and logging

- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/steps/coding_step.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/autofix/steps/solution_step.py
- src/seer/automation/autofix/steps/steps.py
- src/seer/automation/pipeline.py
Instead of preserving errored steps that are then retried, we delete the errored step. On the frontend, the content of the errored step disappears and the new one starts with a message like this:
> chore(autofix): Deletes errored steps when retrying

- src/seer/automation/autofix/components/insight_sharing/component.py
The problem was that if the repo name from the insight was invalid (e.g. "N/A" because the LLM knew there were no accessible repos), then autocorrect would return None. Passing None into get_repo_client would pick a non-accessible repo if that was the only one.
So we just make sure that we have a repo name before trying to get a repo client.
> fix(autofix): Add None check for repo names in insight sharing

- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/app.py
- tests/test_seer.py
With our current API, the same detection endpoint is serving three different use cases that need three different SLAs. It is hard to monitor and alert on breaches for each one. This PR ensures that transaction of each use case has unique identification.
> chore(anomaly-detection): separate transaction names for the different operations

- src/seer/automation/models.py
- tests/automation/test_automation_models.py
- Reduce token count by ignoring is_transaction and empty errors keys
- Reduce indent amount from 4 -> 2 spaces
- Should save 3-6 tokens per span which adds up over 100-1000s of spans
To Do Next:
- autogrouping spans (similar to the trace waterfall with some simple heuristics
- review if truncating descriptions or long keys impacts results
> chore(trace summary): Reduce token count

- src/seer/automation/autofix/autofix_context.py
- tests/automation/autofix/test_autofix_context.py
Prioritizes repo name over owner name in the autocorrect logic.
> fix(autofix): Smarter repo name autocorrect

- src/seer/automation/codegen/evals/datasets.py
Langfuse UI sucks and was making it hard for me to understand the actual status of the system. No doubt because this is early runs and whatnot.
I probabl should have asked what we use for real, but I didn't, and just built this real quick to get some better aggregated results.
So there you go.
to run:
```
make shell
python src/seer/automation/codegen/evals/datasets.py run-report --dataset-name relevant-warnings --run-name 3rd-full-run
```
The output looks like this:
```
==========================================
Run 3rd-full-run
==========================================
┌─────────────────────────────┬────────┬────────────┐
│ Metric                      │  Count │ Percentage │
├─────────────────────────────┼────────┼────────────┤
│ Total items                 │     47 │    100.00% │
│ …
```
> utility to see run results

- src/seer/automation/codebase/repo_client.py
When a `urllib3.Retry` object (which `GithubRetry` inherits from) hits a retryable exception, it creates a new instance. To configure the backoff limit across instances, need to set the class attribute, not the instance attribute.
> Fix GH retry backoff limit

- requirements-constraints.txt
- requirements.txt
- src/seer/automation/autofix/tools/tools.py
- src/seer/automation/codebase/repo_client.py
- src/seer/automation/codebase/repo_manager.py
- src/seer/db.py
- tests/automation/autofix/test_autofix_tools.py
- tests/automation/codebase/test_repo_manager.py
This PR changes how we download repos from downloading repo archives to cloning the repo with `depth=1` and then checking out a specific commit sha.
- This sets us up to be able to cache and load repos from GCS using this `RepoManager`
- As the repo is downloading, we also update the Autofix state to ensure that the state does not get timed out
Introduce the `RepoManager`, conceptually it's supposed to be the class that manages a repo's download, caching etc. It should encapsulate the entire lifecycle of a downloaded repo. It's also entirely source control provider agnostic, and instead relies on getting passed a `RepoClient` that it interacts with.
1. The tools are initialized, the `RepoManager`s are created and then called to initialize each on its own thread in the background.
2. The …
> feat(autofix): Use a git client to clone and checkout repos

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/components/coding/component.py
- src/seer/automation/autofix/components/insight_sharing/component.py
- src/seer/automation/autofix/components/solution/component.py
- src/seer/automation/autofix/tools/tools.py
- tests/automation/autofix/components/test_insight_sharing.py
- Adds an autocorrect method for file paths in `autofix_context`. (not refactoring `attempt_fix_path` inside tools because then codecov can't use it)
- Then uses it to autocorrect the file name in the insight card sources so that we don't generate invalid links. 
- Also adds it to memory prefill steps.
- Also fixes autocorrect for file path in expand document not being used
> fix(autofix): Use more file path autocorrect 

- src/seer/automation/assisted_query/assisted_query.py
- src/seer/automation/assisted_query/create_cache.py
- src/seer/automation/assisted_query/prompts.py
- tests/automation/assisted_query/test_create_cache.py
- Reduce amount of fields for the values query to max 125
- Ensure we query for some of the most important fields (spans, project, transaction, trace, etc)
- Should fix timeout issues for projects with lots of fields
- Also clean up some logs
> chore(trace queries): Reduce fields used in values query

- requirements-constraints.txt
- requirements.txt
- src/celery_app/app.py
- src/seer/automation/agent/client.py
- src/seer/bootup.py
- src/seer/logging.py
Our logging was a mess with duplicated logs, hard to read json format, and complicated implementation.
This PR simplifies that by using the standard logger, with a substring filter that filters out noisy logs. Especially needed now that we show these logs in Sentry.
May the screenshots below be all the rest of what I have to say.
> fix(seer): Fix the logging

- src/seer/automation/assisted_query/assisted_query.py
- tests/automation/assisted_query/test_assisted_query.py
- Ensure certain fields are _always_ a part of the LLM's search as these tend to provide the most information
- These fields should be available on every span (span.op, span.description, span.transaction)
- Refactor tests to pytest asserts
> chore(trace query): include required fields

- src/seer/automation/codegen/evals/datasets.py
- src/seer/automation/codegen/evals/evaluations.py
- src/seer/automation/codegen/evals/models.py
The idea of mocking PrFiles in the evals was to allow us to run them without reaching out to GitHub. However with the move to the agentic approach this is useless. The agents have code searching capabilities, and are expected to communicate quite often with GitHub anyway.
So when running evaluations the GitHub token you have in `.env` needs to be able to access all the repos for which there are eval items.
> chore: don't mock PrFiles when running evaluations

- src/seer/automation/autofix/autofix_context.py
In `make_file_patches`, we fetched the original content from github for all files, even newly created files, causing `UnknownObjectException` (this error was handled just fine though, so no impact). This PR makes it so we only fetch the original file for edit and delete changes to avoid logging this error and avoid an unnecessary API call.
Root cause discovered by Autofix 🤯 :
Autofix attempted to fetch original content for a new file proposed in changes, which did not exist at the reference commit SHA.
The `autofix_change_describer_task` Celery task is the entry point for this part of the Autofix pipeline. It initializes the `AutofixChangeDescriberStep` and invokes its execution.
(See seer/automation/autofix/steps/change_describer_step.py)
The `_invoke` method of …
> fix(autofix): Don't fetch original content for new files

- src/seer/automation/autofix/tools/tools.py
- src/seer/automation/codebase/repo_manager.py
The codegen request doesn't have an org id and for some reason linter didn't throw a fit??
> fix(autofix): Still make repo manager work without org id

- src/seer/automation/autofix/components/insight_sharing/component.py
- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/components/solution/models.py
- src/seer/automation/autofix/event_manager.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/autofix/steps/solution_step.py
- src/seer/automation/codebase/repo_client.py
- tests/automation/autofix/components/test_insight_sharing.py
- tests/automation/autofix/test_autofix_event_manager.py
Generates urls for root cause and solution timeline items:
- in root cause, if there's a relevant code file, generates a url. If there seems to be a code snippet, try to fuzzy match it to the file content to get the line numbers
- in solution, if there's a relevant code file, generates a url. Does not attempt to match because this is mostly new code.
> feat(autofix): Generate urls for root cause and solution timeline items

- src/seer/automation/autofix/tools/tools.py
Moved too fast; need to check the request not the context
> fix(autofix): Check the request not the context in repo tools

- src/seer/automation/autofix/runs.py
- src/seer/automation/preferences.py
- tests/automation/autofix/test_runs.py
- tests/automation/test_project_preferences.py
When you never visit the seer settings page or you have disabled integrations, the seer preferences object is never created. This means we just keep using the code mappings repos even when on the seer settings page there are no repos listed.
This PR makes sure the preferences object is created, even if the repo list is empty. This way what you see in settings matches the actual repos Autofix runs on. Code Mappings from now on will only be used on the first run only.
Fixes https://linear.app/getsentry/issue/AIML-395/fix-seer-preferences-creation
> fix(autofix): Create preferences object on an Autofix run

- src/seer/automation/assisted_query/assisted_query.py
- src/seer/automation/assisted_query/create_cache.py
- src/seer/automation/assisted_query/models.py
- src/seer/automation/assisted_query/prompts.py
- src/seer/automation/assisted_query/utils.py
- Default to no values if cache not immediately available upon request
- Fetching values is the longest step of the caching process so skipping this should result in a very minimal cold start
> chore(trace queries): Default cache

- src/seer/automation/codegen/evals/evaluations.py
Based on [this deep dive](https://www.notion.so/sentry/4th-full-run-1f18b10e4b5d808ea1f3c68bb2661136) for one of the runs in the dataset it seems like the evaluator LLM was not so focused on the content when matching bugs, but would use the location as a criteria too
The small changes in the prompt make it focus more on the content when matching, and not so much on location. I noticed that 2 matched bugs with low content score were no longer matched, but we kept the one with a high content score (all 3 had pretty good location scores)
And that's all the 3 bugs we had matched :D so, there you go.
> chore: prompt change to evaluations (relevant-warnings)

- tests/automation/autofix/test_autofix_tasks.py
- tests/automation/summarize/test_trace.py
VCR tests endpoint changed, thus failing.
Was gonna update the `test_summarize_trace_success`, but testing for the exact output makes it very brittle, we should instead make the test a bit looser imo.
> ci: Skip some vcr tests for INC-1163

- src/seer/automation/codebase/repo_manager.py
- tests/automation/codebase/test_repo_manager.py
Make an authenticated fetch when syncing. Also, remove the origin url when archiving during pruning.
Fixes SEER-15E
> fix(autofix): Fix fetch auth + remove origin when pruning

- src/seer/automation/autofix/runs.py
- src/seer/automation/preferences.py
- tests/automation/test_project_preferences.py
Cap number of repos per project on the backend to 8.
Including trace-connected repos, cap it at 12.
> fix(autofix): Cap number of repos in prefs

- .github/workflows/tests.yml
- gocd/templates/bash/check-github.sh
The main branch's CI `Finish Tests` step will be named uniquely, and have GoCD check for it.
> ci: Make the main branch check named differently

- src/seer/automation/assisted_query/assisted_query.py
- src/seer/automation/assisted_query/create_cache.py
- tests/automation/assisted_query/test_assisted_query.py
- tests/automation/assisted_query/test_create_cache.py
- Used the wrong key name when reviewing response from seer_rpc
- Used "fields_values" instead of "values"
- Previously was silently failing (defaults to {} or [] if the key is incorrect)
- Now if it is the wrong key, then we log the issue rather than failing silently
- Also if there are other issues with the RPC response
- Note: we _can_ receive responses with no results depending on the keys passed in, but now we log them so we at least know if its a failure or not
> fix(assisted queries): Key name and log failures

- src/seer/automation/agent/client.py
- Include thinking budget param in LlmClient.generate_structured()
Tested locally again too:
> fix(trace-queries): include thinking budget in llmclient

- src/seer/automation/autofix/evaluations.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/runs.py
- tests/automation/autofix/test_autofix_evaluations.py
This is so when we run evals we don't save the repo configuration nor read from it
> fix(autofix-evals): Fix evals not using passed repo config

- src/seer/automation/agent/client.py
- tests/automation/agent/test_client.py
Handles the stream output in a separate "producer" thread for each llm text stream generator. This allows langfuse to still work as normal because the `@observe` decorator is outside the thread.
Tested locally with both pre-first token and post-first-token timeouts
> fix(autofix): Fix freezing LLM stream freezing the timeout check

- src/seer/automation/codebase/repo_client.py
- tests/automation/codebase/test_repo_client.py
The method to get the full git tree was broken on large repos. This was because when building the tree recursively, turns out tree items from that point only return paths relative to the subdirectory you made the request for. We needed to reconstruct the full path from the root of the repo. Previous testing of this method only compared the count of files, so this slipped through.
This should fix the bug where expand document (and other things like autocorrect, stack trace validation, and more) were breaking on large repos 🙏 
Tested with a script that compared git tree results and cloned repo results. Tried on `getsentry/seer` and `torvalds/linux`.
> fix(repo client): Fix get git tree

- src/seer/anomaly_detection/anomaly_detection.py
- src/seer/anomaly_detection/models/external.py
- tests/seer/anomaly_detection/test_anomaly_detection.py
The value error is too generic and overloaded as any of our end points can throw this error without any context. Also, the error from anomaly detection endpoint is high volume and low priority. So separating it out.
> chore(anomaly-detection): separate out the AD null value error to track it separately with lower priority

- src/seer/automation/autofix/tools/tools.py
- src/seer/automation/codebase/repo_client.py
- tests/automation/autofix/test_autofix_event_manager.py
- tests/automation/autofix/test_autofix_tools.py
- tests/automation/codebase/test_repo_client.py
When creating a file via a tool, we called get_file_content to validate that the file didn't already exist. This had the disadvantages of:
1. Making an API call
2. Throwing an error to Sentry
This PR switches to get_valid_file_paths, which should already be cached in the coding step.
> chore(autofix): Don't log error when creating file

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/tools/tools.py
- src/seer/automation/codegen/codegen_context.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/autofix/test_autofix_tools.py
Two problems:
- we didn't read newly created files in `_attempt_fix_path`, so the agent could not edit its own files
- `does_file_exist` didn't take into account newly created files either, so we ended up with duplicates sometimes
> fix(autofix): Fix claude tools file creation logic

- src/seer/automation/codegen/evals/models.py
if `more_readable_repos` is in the input of the dataset item, the agent can search across the PR repo and these repos. would like to add getsentry/sentry for the seer PRs in our dataset
> Support multi-repo search in evals

- src/seer/automation/autofix/tools/tools.py
- src/seer/automation/codebase/tasks.py
Scale the time limit for a repo according to it's size on metadata. So for example, a 5GB repo would have a `15 + (5 - 1) * 7 = 43 min` timeout. Any repo less than 1GB would have the default 15 minute timeout.
> feat(repo-manager): Scaling backfill time limit to repo size

- src/seer/automation/autofix/autofix_context.py
- src/seer/automation/autofix/tools/tools.py
- tests/automation/autofix/test_autofix_tools.py
If the claude view command was called with a directory path, our check was not working correctly. This should fix it and return the tree for the path. Should fix [SEER-145](https://sentry.sentry.io/issues/6593399718/).
Tacking on: modify `get_file_contents` in `AutofixContext` to not unnecessarily call GitHub if the file is a locally created file. Should fix [SEER-EB](https://sentry.sentry.io/issues/6045489887/).
> fix(autofix): Handle view directory in claude tools

- src/integrations/overwatch/overwatch_auth.py
- src/seer/app.py
- src/seer/automation/codegen/pr_review_coding_component.py
- src/seer/automation/codegen/pr_review_step.py
- src/seer/automation/codegen/tasks.py
- src/seer/configuration.py
- tests/automation/codegen/test_pr_review.py
- tests/automation/codegen/test_pr_review_coding_component.py
- tests/integrations/test_overwatch_auth.py
This will enable AI PR review (and eventually unit test gen) for Sentry Prevent. 
The goal here is to support 2 apps, Codecov AI, and Autofix(Seer by Sentry). `Overwatch`, which is already setup to communicate with seer, will send requests to initiate reviews and unit tests by hitting this endpoint. 
Post migration on Codecov's side, we can remove the `codecov-request` endpoint and use `overwatch-request` for all our needs. A refactoring effort will also be required to change all our variable and class names at that time.
> [ft] Add overwatch request endpoint

- src/seer/automation/autofix/components/root_cause/models.py
- src/seer/automation/autofix/components/solution/models.py
- src/seer/automation/autofix/models.py
- src/seer/automation/autofix/steps/root_cause_step.py
- src/seer/automation/autofix/steps/solution_step.py
- src/seer/automation/models.py
- tests/automation/test_automation_models.py
Receives logs from `sentry` in the initial Autofix request. Unused for now as I want to make sure it works. Then I'll follow up and include them in the prompt
> feat(autofix): Receive logs from sentry in initial request

- tests/automation/codegen/test_retry_unit_test_coding_component.py
[my deploy failed](https://github.com/getsentry/seer/actions/runs/15333105668/job/43144410334) for a PR that's independent of this code b/c it looks like these API calls finally failed after some API change(?). pretty sure these need to be mocked
> Mock CodecovClient API calls

- src/seer/automation/summarize/issue.py
- src/seer/inference_models.py
- tests/automation/autofix/test_autofix_context.py
- tests/automation/summarize/test_issue.py
finetuned model on:
1. issue summaries from issues which had a PR linked to it
2. synthetic negatives from gemini-2.5-pro based on common classes of false positives for the current model, especially tricky string parsing, and errors caused by intentionally not handling a bad request. in its current state, issue summary often doesn't capture the latter well. but the idea is that training the model on them will make it more backwards compatible / less sensitive to what issue summaries look like if better signal comes out. can always retrain but wanted to do this anyway. my next experiment is to get better signal out of issue summary
[updated training notebook](https://github.com/getsentry/data-analysis/blob/main/autofix/issue_summary/autofixability/train.ipynb)
> fix(fixability): Train on PR-issue links, more synthetic negatives

- src/seer/automation/assisted_query/assisted_query.py
- src/seer/automation/assisted_query/models.py
- src/seer/automation/assisted_query/prompts.py
- tests/automation/assisted_query/test_assisted_query.py
- Return query options directly if
- System does not need more context on fields or values
- User submits a gibberish query (return some sort of general, but default result)
- Reduce latency to ~0.5-3 seconds when further context is not required and results in 1 llm call instead of 2
> chore(trace queries): Short Circuit Queries

- src/seer/automation/codebase/repo_manager.py
- tests/automation/codebase/test_repo_manager.py
Use `get_valid_file_paths` to remove unreadable files from downloaded repos. Often times the agent would get confused if `ripgrep` or `find` named a file that `expand_document` could not then access
> fix(autofix): Only keep valid files in repo download

- src/seer/automation/agent/client.py
The prior condition was incorrect, revert to original europe-west-4 for sonnet us:
https://github.com/getsentry/seer/blob/30a025c5835d3b96b1fde216ba809380bc8715e4/src/seer/automation/agent/client.py#L556-L564
> fix(autofix): Claude use eu-west-4

- src/seer/automation/agent/client.py
- tests/automation/agent/test_client_fallback.py
We weren't correctly fallbacking on retryable exceptions. Any exception that's retryable should be fallbackable.
> fix(llm-client): Fallbacking should trigger on retryable exceptions
